### ISSUE TITLE
Deployment stuck while importing ads.txt

### ISSUE THREAD

**Issue by hajalae** [aws-amplify/amplify-hosting#1975] opened 2021-06-17 22:23 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

du4whihpfaa71

### Region

eu-west-3

### Amplify Console feature

Manual deploys

### Describe the bug

Hi,

I wanted to add the adsense module to my application. Therefore, I was asked to add the ads.txt provided by google adsense in order to configure my website.

Unfortunately when I include the ads.txt file to my build folder, and try to manually deploy by drag and drop, the deployment get stuck and I have the "Retrieving deployment details..." message. I am not able to cancel the deployment.

I tried to create a new application to see if it's the ads.txt file that was creating the issue, and indeed it is. Without the ads.txt file, the deployment works fine. But as soon as I put the file in my build folder, the deployment get stucked

### Expected behavior

The expected behaviour is that the deployment shouldn't be stucked in the "Retrieving deployment details..." phase.

### Reproduction steps

1. Building my reactjs app
2. Put the ads.txt file provided by google adsense to my build folder
2. Connect to my aws Amplify console
3. Drag and drop my build folder
4. Deployment get stucked...

**Comment by calavera** [comment] 2022-04-18 22:09
Sorry for the late reply. Since it's been a long time since this was open, I'm going to close it because we don't have enough information to reproduce it. Let us know if you want us to investigate further and we'll happily reopen the issue.

**Closed by calavera** 2022-04-18 22:09 UTC
