### ISSUE TITLE
Next v13 - Failed to write image to cache, no such file or directory, '/var/task/.next/cache/images'

### ISSUE THREAD

**Issue by ChristopherTrimboli** [aws-amplify/amplify-hosting#3150] opened 2022-11-27 22:07 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2qsreobkyv1ck

### AWS Region

us-west-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

Everything builds and deploys successfully in the main Amplify console.

However my site is not live.

Looking deeper into the Hosting Compute CloudWatch logs... I see 1 error.

```
Failed to write image to cache zAA2roPYxRUt5NQhsSiXUIKgjUj4Li12X83poniamyo= [Error: ENOENT: no such file or directory, mkdir '/var/task/.next/cache/images'] {
--
 errno: -2,
code: 'ENOENT',
 syscall: 'mkdir',
path: '/var/task/.next/cache/images'
}
```

I have run the `next build` and `next start` on local machine. Do not get this issue.
I have also made sure to install `sharp` package recommended for production images.

I have 1 image in project. Very simple project, basically a brand new template create-next-app running v13. Nothing fancy.

### Expected behavior

Does not error and site is accessible.

### Reproduction steps

Host a Next v13 app with an `<Image />`.

Hopefully it errors?

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment] 2022-11-28 21:02
Hi  @ChristopherTrimboli unfortunately I wasn't able to reproduce this issue when using `next/image` but it looks like your site is up and the image is visible now. Can you confirm if you are still running into this issue?

**Comment by swaminator** [comment] 2022-11-29 21:39
@ChristopherTrimboli we are working on a fix for this issue.

**Comment by ChristopherTrimboli** [comment] 2022-11-29 21:41
My site is fixed, unrelated to this issue... but I think I found a different bug for you guys :D 

I am sorted, appreciated.

**Comment by hloriana** [comment] 2022-11-30 23:32
@ChristopherTrimboli if you found a different bug, please feel free to create a new issue with the bug report template so we can assist you. Thank you!

**Closed** 2022-11-30 23:46 UTC
Labels: bug, pending-prioritization, compute
