### ISSUE TITLE
Amplify get stuck on deploy after test phase

### ISSUE THREAD

**Issue by rubfergor** [aws-amplify/amplify-hosting#1167] opened 2020-10-26 19:12 UTC
Hi,

I'm running a site using a Create React App monorepo. The first build was successful, but after I added a test section Amplify run the tests and tries to publish the test artifacts instead of the frontend ones in a similar scenario to #1160. If I don't put anything in the artifact section of the test, the build complete but the test phase fails but if I put a dummy file with a report from jest it get stuck on deployment after saying that it has published my test artifacts.

```
2020-10-26T18:46:27 [INFO]: Starting Deployment
2020-10-26T18:46:27 [INFO]: Updating Edge config
2020-10-26T18:46:27 [INFO]: Start deploying test artifact
2020-10-26T18:46:27 [INFO]: Deploying coverage/clover.xml
2020-10-26T18:46:27 [INFO]: Deploying coverage/coverage-final.json
2020-10-26T18:46:27 [INFO]: Deploying coverage/lcov-report/base.css
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov-report/block-navigation.js
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov-report/favicon.png
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov-report/index.html
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov-report/prettify.css
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov-report/prettify.js
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov-report/sort-arrow-sprite.png
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov-report/sorter.js
2020-10-26T18:46:28 [INFO]: Deploying coverage/lcov.info
2020-10-26T18:46:28 [INFO]: Deploying coverage/report.html
2020-10-26T18:46:29 [INFO]: Finish deploying test artifact
```

For reference, my region is us-east-1 and my appId is d1s2p57h03rwzi, in build 5 or previous. My YAML file is this:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12
        - yarn install
    build:
      commands:
        - yarn frontend:build
  artifacts:
    baseDirectory: /frontend/build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
backend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12
        - yarn install
    build:
      commands:
        - if [ "${AWS_BRANCH}" = "prod" ]; then yarn services:deploy-all --stage prod; else yarn services:deploy-all; fi
  cache:
    paths:
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - nvm use $VERSION_NODE_12
        - yarn install
    test:
      commands:
        - yarn test
    postTest:
      commands:
        - git config --global user.email $GIT_EMAIL
        - git config --global user.name $GIT_USER
        - git checkout ${AWS_BRANCH}
        - yarn release
        - git remote set-url origin "https://oauth2:${GIT_TOKEN}@${GIT_REPO_URL}" # this is needed to use the token with gitlab
        - git push --follow-tags origin HEAD
  cache:
    paths:
      - node_modules/**/*
  artifacts:
    files:
      - coverage/**/*
    baseDirectory: ./

```

**Comment by gwryssekk** [comment] 2020-10-27 16:58
Hi @rubfergor -- I'm looking into this.

**Comment by lorenzk** [comment] 2020-10-29 13:20
We are having the same issue. Our preview app deployment hangs on `Finish deploying test artifact` indefinitely. We are using Cypress for our tests. 

- App id: `d1zweq2xy6txw5`
- Region `eu-central-1`

<details>
<summary>amplify.yml</summary>

```
version: 1

backend:
  phases:
    build:
      commands:
        # Try resetting the cache to fix env issues
        # - envCache --set stackInfo ""
        # Execute Amplify CLI with the helper script'
        - amplifyPush --simple

frontend:
  phases:
    preBuild:
      commands:
        - nvm use 12
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - ~/.cache

test:
  phases:
    preTest:
      commands:
        - nvm use 12
        - yarn install --frozen-lockfile
        - yarn run cypress install
    test:
      commands:
        - yarn test:ci
  artifacts:
    baseDirectory: coverage
    files:
      - '**/*'

  cache:
    paths:
      - ~/.cache
```
</details>

I moved the tests into the build phase as a workaround (hat tip to https://github.com/aws-amplify/amplify-console/issues/115#issuecomment-711909621).

**Comment by sugi-s** [comment] 2020-11-02 08:43
@litwicki @gwryssekk we are facing similar issue when running Testcafe e2e tests in test phase.....

_Logs from deploy phase:_
`2020-11-02T08:24:28 [INFO]: Starting Deployment
2020-11-02T08:24:28 [INFO]: Start deploying test artifact
2020-11-02T08:24:28 [INFO]: Deploying test-report.json
2020-11-02T08:24:28 [INFO]: Finish deploying test artifact
2020-11-02T08:24:28 [INFO]: Updating Edge config`

_Here is the appId:_
appId: d1n442ck0l1wax
region: eu-west-1
concerned branch is in preview (PR) (pr-108.d1n442ck0l1wax)

However we are running same set of Testcafe tests in develop as part of build phase and it works.....

**Comment by litwicki** [comment] 2020-11-10 07:55
@sugi-s  This particular scenario is something we are investigating a root cause for and prioritizing as soon as we can. In the meantime are you able to use the workaround proposed?

**Comment by Alk3m1st** [comment] 2020-11-12 06:12
Just noticed this issue and it's similar to what I was experiencing. In my case I was missing configFilePath in the tests > artifacts section. Once I added that pointing to my test report file it starting working. An example is configFilePath: '**/mochawesome.json' as in the documentation here - https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html (just before the disabling tests section).
Hope it helps.

**Comment by rubfergor** [comment] 2020-11-20 21:53
Hi @litwicki !

Is there any advance? Can I help you somehow in debugging the issue?

**Comment by litwicki** [comment] 2020-11-21 00:00
@rubfergor we have not started working on the permanent fix for this issue yet. Are you able to use the workaround proposed here: https://github.com/aws-amplify/amplify-console/issues/1167#issuecomment-725862271

**Comment by sugi-s** [comment] 2021-01-12 11:19
@litwicki  Any updates with this issue??? With the workaround we cannot download the screenshots and it is getting difficult to debug issues when there are test failures in CI pipeline. Appreciate if this can be looked into

**Comment by rubfergor** [comment] 2021-01-15 09:19
@litwicki no, I wasn't able to get it up and running with that

**Comment by litwicki** [comment] 2021-01-16 03:50
@rubfergor @sugi-s we're looking at a comprehensive approach to resolving this issue permanently that is taking longer than we had originally thought to properly design. We'll be focusing on that with a majority of the team next week and will share updates as we have them.

**Comment by m-p-d** [comment] 2021-02-04 11:28
+1 for resolving this issue with some urgency. @litwicki please let us know expected timeline for a fix, as it was already several weeks since you mentioned your team would focus on this 🙏

**Comment by monscamus** [comment] 2021-02-04 17:01
Managed to resolve the deployment failure by including all possible parameters (even though I'm not using them as in Alchemists post).

For anyone doing a similar test regime:

`test:
  phases:
    test:
      commands:
        - npm run-script test -- --watchAll=false --outputFile=outputTests.json --json
  artifacts:
    files:
        - '**/outputTests.json'
    baseDirectory: __test__
    configFilePath: '**/jest.config.js'
`

> Just noticed this issue and it's similar to what I was experiencing. In my case I was missing configFilePath in the tests > artifacts section. Once I added that pointing to my test report file it starting working. An example is configFilePath: '**/mochawesome.json' as in the documentation here - https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html (just before the disabling tests section).
> Hope it helps.

**Comment by hanna-becker** [comment] 2021-05-02 20:31
Thanks, @monscamus. We had the same issue for months and had just started moving everything over to gitlab-ci because of that. What frustrates me is not that the Amplify CI requires you to set that parameter even when it's not required (I can live with that), but that there was no useful error message int he pipeline. The Deploy stage would only these two lines:
```
2021-04-27T12:14:00 [INFO]: Starting Deployment
2021-04-27T12:14:01 [ERROR]: Failed to deploy
```
How on earth were we supposed to guess that there is a syntax error in the test stage of the amplify.yml from that? Using the Amplify CI is a terrible user experience at the moment, because of not providing any useful error logs when things go wrong. Please, Amplify console team, prioritize fixing this.

**Comment by swaminator** [comment] 2024-03-20 20:13
Resolving this issue as we have not observed issues with this after we fixed deployment failures.

**Closed by swaminator** 2024-03-20 20:13 UTC
Labels: bug, pending-prioritization
