### ISSUE TITLE
deployment requires new notification resource creation stuck in ci/cd

### ISSUE THREAD

**Issue by sundersc** [aws-amplify/amplify-hosting#2592] opened 2022-02-18 21:29 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d11dtbgh84vt88

### Region

us-east-1

### Amplify Console feature

Backend builds

### Describe the bug

While using continuous deployment, if an environment requires to create a notification resource (on git push), the workflow is stuck with a prompt to amplify-cli and the build fails.

2022-02-16T21:57:30.723Z [WARNING]: - Building custom resources
2022-02-16T21:57:30.831Z [WARNING]: ✔ Successfully pulled backend environment main from the cloud.
2022-02-16T21:57:30.856Z [WARNING]: - Retrieving channel information for APNS.
2022-02-16T21:57:30.902Z [WARNING]: ✔ Channel is not setup for APNS
2022-02-16T21:57:30.903Z [WARNING]: - Retrieving channel information for FCM.
2022-02-16T21:57:30.937Z [WARNING]: ✔ Channel is not setup for FCM
2022-02-16T21:57:30.937Z [WARNING]: - Retrieving channel information for Email.
2022-02-16T21:57:31.022Z [WARNING]: ✔ Channel is not setup for Email
2022-02-16T21:57:31.022Z [WARNING]: - Retrieving channel information for SMS.
2022-02-16T21:57:31.059Z [WARNING]: ✔ Channel is not setup for SMS
2022-02-16T21:57:31.068Z [INFO]: ? Choose authentication method used for APNs (Use arrow keys)
                                 ❯ Certificate
                                 Key

### Expected behavior

Build should take the values from environment variable and build should succeed.

### Reproduction steps

1. Create a react app `npx create-react-app testapp`.
2. Run `amplify init`, create `main` environment.
3. Add an api `amplify add api` and push the changes to the cloud `amplify push -y`.
4. `amplify add hosting` and setup continuous deployment and connect git branch `main`.
5. Create another git branch `beta`.
6. On console, click `Connect Branch` and setup frontend deployment for `beta` branch.
7. Create a new backend environment 'beta`.
8. On `main` amplify environement, run `amplify add notifications` and enter the value for the prompts and complete the workflow. Commit git branch `main`.
9. Now checkout to `beta` git branch, checkout amplify environment `beta`. Make some code changes and git commit.
10. Deployment will fail in amplify console because of the amplify-cli prompt given in the description.

**Comment by sundersc** [comment] 2022-02-18 21:31
**Workaround:**
1. Download the most recent amplify cli. (npm i -g @aws-amplify/cli).
2. From the project folder, pull the recent changes of healthy environment (`main`) from cloud backup using 'amplify pull' command.
3. Now switch to the problematic environment using 'amplify env checkout beta'.
4. If you notifications configurations are missing for the environment, CLI will prompt to enter those values.
5. Do 'amplify push' to push the changes to the cloud.
6. Any further code changes can be done through the CI/CD (git push). This workaround is required only if there are any updates required to the notifications resource.

**Comment by hloriana** [comment] 2022-02-21 17:10
Hi @sundersc 👋🏽 thank you for opening this issue and for providing detailed reproduction steps. We will reproduce the behavior and add it to our backlog.

**Comment by gspeicher** [comment] 2022-10-20 17:24
This was never a problem for us in the past but is now an issue since CLI 10.3.0 was released. It is prompting us for APNS/FCM/Email notifications settings every time we do a pull, whether it is headless or interactive.

**Comment by gspeicher** [comment] 2022-10-20 17:44
Seems possibly related to #3042

**Comment by Jay2113** [comment] 2024-02-21 21:47
This issue was fixed with Amplify CLI v10.4.0: https://github.com/aws-amplify/amplify-cli/issues/11238#issuecomment-1295067101.

**Closed by Jay2113** 2024-02-21 21:47 UTC
Labels: bug, backend-builds
