### ISSUE TITLE
Unable to connect a new branch: backend fails creation because the branch already exists

### ISSUE THREAD

**Issue by ludokx** [aws-amplify/amplify-hosting#2152] opened 2021-08-11 21:04 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

duwnea65ixsek

### Region

us-west-2

### Amplify Console feature

Backend builds

### Describe the bug

I've been trying to connect a new branch (along with a new environment of the same name) to my project for days now and it keeps failing. I have two branches (`main` and `dev`) that are connected and work just fine. I wanted to create a new `demo` environment off of a new `demo` branch that is the exact same one as `main`. After connecting the branch, the build kicks off but fails with an error saying that the branch (`AmplifyBranch`) can't be created because it already exists.

```
2021-08-11T20:49:58.857Z [INFO]: CREATE_FAILED AmplifyBranch                                               AWS::Amplify::Branch       Wed Aug 11 2021 20:49:56 GMT+0000 (Coordinated Universal Time) Resource handler returned message: "Invalid request provided: Failed to create branch. The branch demo already exists for the app XXX (Service: Amplify, Status Code: 400, Request ID: 824b01c2-a528-41f1-b3bc-4fac41fb647a, Extended Request ID: null)" (RequestToken: XXX, HandlerErrorCode: InvalidRequest)
```

I've looked at similar issues that mentioned `amplifyPush --simple` but that's how it's already set up currently.

### Expected behavior

The new `demo` environment should be created successfully and deployed, just like all my commits to `dev` and `main` work fine. Also the branch has to be available in the Git repo otherwise it can't be connected.
It seems like something in the Amplify internals is not being cleaned up correctly.

### Reproduction steps

1. Create a new branch `demo` off of `dev` or `main`, push it to the remote
2. Connect the branch on the Amplify console. 
  a. Select the branch 
  b. Select "Create new environment" (and leave environment name empty to create the same name as the branch)
3. Click "Save and deploy"
4. Wait for build to fail with error above

### Build Settings

```yaml
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by Athena96** [comment] 2021-08-12 18:18
Hi @ludokx has the build failed because the branch already existed from the very start, or did it fail with a different error the first time?
Can you try disconnecting the branch, and deleting the backend environment, then re connect the branch following the same steps you list?

**Comment by ludokx** [comment] 2021-08-12 18:34
> Hi @ludokx has the build failed because the branch already existed from the very start, or did it fail with a different error the first time?

Hi @Athena96 the build always failed with the same error. I tried another branch name and same issue.

> Can you try disconnecting the branch, and deleting the backend environment, then re connect the branch following the same steps you list?

I also already tried disconnecting the branch, deleting the backend environment and reconnecting it. It's always the same issue unfortunately

**Comment by Athena96** [comment] 2021-08-12 23:48
@ludokx can you confirm if the s3 bucket for your backend still exists in your account? It should have the prefix of `amplify-*` and would include `dev` in the bucket name

**Comment by ludokx** [comment] 2021-08-12 23:53
@Athena96 yes I have it for `dev`, `main` (actually named `prod`) and `demo`

**Comment by ludokx** [comment] 2021-08-13 00:17
> @Athena96 yes I have one for `dev`, `main` (actually named `prod`) and one older for `demo` which seems to not have been deleted. I'll try to delete that bucket and reconnect the branch again.

Unfortunately that failed as well

**Comment by Athena96** [comment] 2021-08-13 21:47
is there also a CloudFormation stack for demo? can you try deleting that as well

**Comment by victorccccc** [comment] 2021-08-20 17:32
Feel free to reopen this if issue persists

**Comment by ludokx** [comment] 2021-09-20 17:41
@Athena96 finally circling back, there is no CloudFormation stack for demo after I deleted everything, I double checked. I tried again to connect the demo branch and it failed with the same issue

**Comment by hloriana** [comment] 2022-11-09 21:38
Closing as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2732. Please track that issue for any updates on the fix for this behavior. Thank you!

**Closed by hloriana** 2022-11-09 21:38 UTC
