### ISSUE TITLE
the app stuck on "pending" forever after dragging the folder

### ISSUE THREAD

**Issue by repepto** [aws-amplify/amplify-hosting#2676] opened 2022-03-30 16:29 UTC
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2outlzd2gbtvh

### Region

eu-central-1

### Step

updating build by dragging folder

### Status

Pending

### Issue or question

The app stuck on "pending" forever after dragging the folder

**Comment by hloriana** [comment] 2022-04-04 20:30
Hi @repepto, I was not able to reproduce this behavior. Can you provide a sample repository that produces this bug? Were you able to successfully update your application before?

**Comment by repepto** [comment] 2022-04-04 22:41
Hi. I v noticed that happens sometimes.  The app may be updated several times very fast but sometimes it stucks on pending for a very long time.  About 10 hours or even more.  Reuploadings don't solve issue. So waiting is only way.Serhii,Best
-------- Original message --------From: hloriana ***@***.***> Date: 4/5/22  02:01  (GMT+05:30) To: aws-amplify/amplify-hosting ***@***.***> Cc: repepto ***@***.***>, Mention ***@***.***> Subject: Re: [aws-amplify/amplify-hosting] the app stuck on "pending" forever after dragging the folder (Issue #2676) 
Hi @repepto, I was not able to reproduce this behavior. Can you provide a sample repository that produces this bug? Were you able to successfully update your application before?

**Comment by hloriana** [comment] 2022-05-09 19:22
So is this only happening after repeatedly updating the app in a short period of time?

**Comment by repepto** [comment] 2022-05-10 03:31
Yes. And sometimes, not every time. Last few updates went smoothly

**Comment by Jay2113** [comment] 2023-06-21 19:50
Hi @repepto 👋 , thanks for your continued patience and apologies for the delayed response on this thread.

Please refer to this FAQ in our troubleshooting guide: https://github.com/aws-amplify/amplify-hosting/blob/main/FAQ.md#deployments-or-jobs-are-stuck-with-a-pending-status-in-the-amplify-console which outlines some potential reasons why the manual deployments can fail while using the `drag and drop` functionality in the Amplify Console.

Our recommendation would be to upload a zip file to an Amazon S3 bucket as this avoids file uploads from the Amplify Console which should offer a higher reliability for manual deployments: https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html#amazon-s3-or-any-url

**Comment by Jay2113** [comment] 2024-02-14 20:58
Closing the issue due to age.

**Closed by Jay2113** 2024-02-14 20:58 UTC
Labels: question, manual-deploy
