### ISSUE TITLE
Redirection to www based url not working

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-hosting#2743] opened 2022-05-09 04:39 UTC
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d280tc8bca7hos

### Region

ap-southeast-2

### Step

WWW Redirection

### Status

NOT WORKING

### Issue or question

Earlier the domain was mapped without [www](http://www/). But now we have configured www and setup a redirect from non www to www.

Unfortunately, it's working for new users only and not for existing ones.

Existing users don't get redirected to www URL until they hard refresh the page and if they again try to load the app without www URL they face same problem again.

Please let me know what could be the reason for this and how it will be resolved.

Thanks,

**Comment by hloriana** [comment] 2022-05-10 22:58
Hi @ParulSharma2622 👋🏽  thank you for raising this issue. We are investigating.

**Comment by benhurley** [comment] 2022-05-10 23:02
Following (having same issue too, dont want to have to port to Route 53 to fix).

**Comment by hloriana** [comment] 2022-05-20 14:07
Closing as duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2652. We will continue to track progress on this bug using issue #2652

**Closed by hloriana** 2022-05-20 14:07 UTC
Labels: bug, custom-domain
