### ISSUE TITLE
Unable to delete application

### ISSUE THREAD

**Issue by michalmyszka** [aws-amplify/amplify-hosting#2888] opened 2022-07-27 10:40 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

dyy9nt7hqf4ga, dyxqb57d6l2wz

### Region

eu-central-1

### Describe the bug

Unable to delete applications with the IDs above.

### Expected behavior

Application to be deleted.

### Reproduction steps

1. Go to AWS Amplify console.
2. Select the application.
3. Select Action -> Delete app.

**Comment by hloriana** [comment] 2022-07-27 20:51
Hi @michalmyszka please run `aws amplify delete-backend-environment --app-id <value> --environment-name <value>` to remove the backend environment. You can then  delete the frontend from the Amplify Console. 

closing as duplicate of  https://github.com/aws-amplify/amplify-hosting/issues/2548

**Closed by hloriana** 2022-07-27 20:51 UTC
Labels: console
