### ISSUE TITLE
The page of cannot be found

### ISSUE THREAD

**Issue by OrelAlon** [aws-amplify/amplify-hosting#3151] opened 2022-11-23 17:11 UTC
**Which Specific Feature is your question related to?**

I uploaded everything correctly, but as soon as I open the site I get an error: The page of cannot be found

**Provide additional details e.g. code snippets**

**Comment by hloriana** [comment] 2022-11-28 19:15
Closing this issue as duplicate of https://github.com/aws-amplify/amplify-hosting/issues/3141

**Closed by hloriana** 2022-11-28 19:15 UTC
Labels: pending-triage
