### ISSUE TITLE
Removing deleted backend environments

### ISSUE THREAD

**Issue by lseemann** [aws-amplify/amplify-hosting#2206] opened 2021-08-26 21:23 UTC
**Please describe which feature you have a question about?**

Backend environment list

**Provide additional details**

I've had several environments get corrupted beyond repair. I've managed to delete them—in some or all of them by deleting their stack in CloudFormation—but they still show up in the list of backend environments.  I would like them to disappear.
Selecting “Delete” from the Actions dropdown does nothing.

**What AWS Services are you utilizing?**

Amplify

**Provide additional details e.g. code snippets**

<img width="657" alt="Screen Shot 2021-08-26 at 4 19 36 PM" src="https://user-images.githubusercontent.com/1102313/131037553-db4d0d1d-31b2-4ac1-8ffa-2a540930549d.png">

**Comment by Narrator** [comment] 2021-12-06 19:26
@lseemann Could you please confirm if you attempted to delete the backends via CloudFormation first before attempting a delete via the AWS Console? 

Also, could you please try the workaround suggested here: [#1330 (comment)](https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-739493860)

**Comment by lseemann** [comment] 2021-12-06 20:08
> @lseemann Could you please confirm if you attempted to delete the backends via CloudFormation first before attempting a delete via the AWS Console?

I did not. Is that the standard procedure?

> Also, could you please try the workaround suggested here: [#1330 (comment)](https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-739493860)

This worked! Thank you!

**Comment by Narrator** [comment] 2021-12-07 04:11
@lseemann That is not the standard procedure and you shouldn't have to delete anything from CloudFormation. However, doing it that way can lead to the state you have described in your issue. Just trying to figure out what steps you took in order to reach the state where you were unable to delete the backend.

Glad the workaround helped you!

**Comment by hloriana** [comment] 2022-07-27 17:04
Closing as duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2548

**Closed by hloriana** 2022-07-27 17:04 UTC
Labels: bug, question

**Comment by johnpc** [comment] 2022-09-27 01:09
When deleting via Amplify console, the issue where the cloudformation stack is deleted out of band from Amplify has been fixed. You should be able to re-try deleting your app from Amplify console.
