### ISSUE TITLE
Nextjs 13 middleware, next/link

### ISSUE THREAD

**Issue by c10ckw0rk** [aws-amplify/amplify-hosting#3352] opened 2023-03-06 05:31 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
# Put output below this line

Bug only occurs in amplify hosting.

```

</details>

### Describe the bug

I have a project where I am using nextjs as a headless CMS. The CMS provides a set of urls which map to different templates, any url can have any template so I am using nextjs middleware to perform rewrites on the urls. 

I have a demo project deployed here (https://danielpe-middleware-refactor.d327zut72dh116.amplifyapp.com/some-random-pathname-1) (Git repo https://github.com/c10ckw0rk/middleware-getserversideprops-standalone-demo).

When using the `next/link` component after you click around for a while the page will just throw an error. Its intermittent, it seems the faster I click through links, the quicker the page errors.  I have also made a component which just does a `router.push` on click of an `a` tag, and the page never breaks (Manual Links are using my component, Next links are using the next/link).

I'm unable to replicate the problem locally, only occurs once the app is deployed amplify. 

### Expected behavior

The page should not error when next links are clicked

### Reproduction steps

Deploy test repo to amplify hosting

### Code Snippet

```javascript
// Put your code below this line.

```
https://github.com/c10ckw0rk/middleware-getserversideprops-standalone-demo

### Log output

<details>

```
// Put your logs below this line
Object { pageProps: {…}, __N_SSP: true, Component: s(n), err: undefined, router: {…} }
some-random-pathname-10:106:22
GEThttps://danielpe-middleware-refactor.d327zut72dh116.amplifyapp.com/favicon.ico
[HTTP/2 404 Not Found 83ms]

Object { pageProps: {…}, __N_SSP: true, Component: s(n), err: undefined, router: {…} }
some-random-pathname-10:106:22
Object { pageProps: {}, Component: s(n), err: undefined, router: {…} }
some-random-pathname-10:106:22
undefined 2 some-random-pathname-10:106:22
Object { pageProps: {}, Component: s(n), err: undefined, router: {…} }
some-random-pathname-10:106:22
undefined 2 some-random-pathname-10:106:22
TypeError: can't access property "map", e is undefined
    NextJS 30
some-random-pathname-10:106:22
TypeError: can't access property "map", e is undefined
    NextJS 30
some-random-pathname-10:106:22
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred some-random-pathname-10:106:22
TypeError: can't access property "map", e is undefined
    NextJS 30
some-random-pathname-10:106:22
TypeError: can't access property "map", e is undefined
    NextJS 30
some-random-pathname-10:106:22
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred some-random-pathname-10:106:22
Error rendering page:  Error: Cancel rendering route
    NextJS 36
some-random-pathname-10:106:22
Object { pageProps: {…}, Component: class ErrorPage, err: TypeError, router: {…} }
some-random-pathname-10:106:22


```

</details>

### aws-exports.js

Not using any configuration

### Manual configuration

Not using any configuration

### Additional configuration

Not using any configuration

### Additional information and screenshots

```json
{
  "name": "middleware-getserversideprops-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "13.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
}
```

**Comment by FacundoSpira** [comment] 2023-08-18 19:35
We found the exact same issue while debugging our application.  We tried recreating a minimal reproducible example. The repository can be found here: https://github.com/FacundoSpira/amplify-nextlink-middleware-error. 
It basically contains the following:
- Three pages `index.tsx`, `page1.tsx` and `page2.tsx` with Links to each of the pages, and a `pre` tag that renders the props that are passed from the `getServerSideProps` function. All pages are identical, only changing the text that is passed as prop on SSR. Here's what index.tsx looks like

```tsx
import type { InferGetServerSidePropsType } from 'next';
import Link from 'next/link';

type HomeProps = InferGetServerSidePropsType<typeof getServerSideProps>;

const Home = (props: HomeProps) => {
  return (
    <main>
      <div>
        <Link href="/">Home</Link>
        <Link href="/page1">Page 1</Link>
        <Link href="/page2">Page 2</Link>
      </div>

      <h1>Server Side Props</h1>
      <pre>{JSON.stringify(props, null, 2)}</pre>
    </main>
  );
};

export const getServerSideProps = () => {
  return {
    props: {
      page: 'Home',
    },
  };
};
export default Home;
```
- A `middleware.ts` file that simple forwards the request with `NextResponse.next();`
```ts
import { NextResponse } from 'next/server';

const middleware = () => {
  return NextResponse.next();
};

export default middleware;

export const config = {
  matcher: ['/((?!static|.*\\..*|_next|favicon.ico).*)', '/'],
};
```

### Expected behaviour
When navigating through the different links, the page should always render the information received from getServerSideProps.

### Actual behaviour
Randomly when navigating through the links, sometimes getServerSideProps return an empty object. That behaviour can be seen on the following video:

https://github.com/aws-amplify/amplify-hosting/assets/58597410/dabb56c6-7069-43de-933c-89fe4ba2047a

### Steps to reproduce
Deploy the repository to amplify and navigate through the links. The linked repository is also deployed here: https://main.d3g9j0bpx2nsb4.amplifyapp.com/

**Comment by jpbalarini** [comment] 2023-08-18 20:00
Same issue here

**Comment by Jay2113** [comment] 2024-03-01 22:35
We are tracking this as a bug here: https://github.com/aws-amplify/amplify-hosting/issues/3704. I'll recommend subscribing to it for any updates. Closing as duplicate.

**Closed by Jay2113** 2024-03-01 22:35 UTC
Labels: transferred, duplicate
