### ISSUE TITLE
Unable to delete Amplify backend environment

### ISSUE THREAD

**Issue by apiel51** [aws-amplify/amplify-hosting#882] opened 2020-07-22 16:52 UTC
** Please describe which feature you have a question about? **
Deleting unused backend environment

** Provide additional details**
I'm trying to remove a deprecated amplify backend environment, but I am getting a "The specified bucket does not exist." error whenever I try to use `amplify pull` to pull the environment so I can delete it. I don't have any resources related to this environment (all deleted) but it doesn't seem like I can delete the environment itself. What's the best way to get around this?

**Comment by ganipcanot** [comment] 2020-07-22 17:24
Can you share your appId/region?

Are you able to delete the baackend environment through the console?:

![image](https://user-images.githubusercontent.com/21091073/88208021-78189080-cc05-11ea-9e32-31c4611122f4.png)

**Comment by apiel51** [comment] 2020-07-22 17:32
Sure. App ID is `d25h3g71gr2w1w` region is `us-west-2` . So I was able to delete the environment using the solution outlined [here](https://github.com/aws-amplify/amplify-console/issues/293) but I am now trying to reprovision an environment with the same name (start new) but the deleted environment (`prod`) is still showing up as an existing environment when trying to link a branch:
![image](https://user-images.githubusercontent.com/17676991/88208763-903cdf80-cc06-11ea-9ca2-31366c5aada7.png)

Where do the options from this dropdown come from?

**Comment by apiel51** [comment] 2020-07-22 18:55
Looking at the network requests it appears that they _should_ be coming from a request to https://us-west-2.console.aws.amazon.com/amplify/api/amplify with an operation value of `listBackendEnvironemnts`. The response from this request is correct and only contains the two backend environments that still exist (dev and master). Perhaps this is some sort of caching bug? @ganipcanot

**Comment by FeliceGeracitano** [comment] 2020-12-10 13:09
I got the same issue:


<img width="900" alt="Screenshot 2020-12-10 at 14 08 44" src="https://user-images.githubusercontent.com/6695231/101776505-53a84c80-3af1-11eb-9a21-46d1ee333f5c.png">

<img width="1590" alt="Screenshot 2020-12-10 at 14 04 42" src="https://user-images.githubusercontent.com/6695231/101776376-1e036380-3af1-11eb-90bc-489b87d4dc65.png">


I've created a BE for testing, but can't delete it via UI

**Comment by marlonmarcello** [comment] 2021-01-06 02:55
Having the same issue, and there is no useful error message at all.
The backend environment in question was automatically created by a PR Review. The PR was closed and deleted and now the backend is stuff and won't go away.

**Comment by sharmaaditya570191** [comment] 2021-02-16 20:09
I am also facing the same issue on Amplify Console. I am not able to delete the whole app or the backend environment on the following configuration:-

- Region: us-east-1
- App ID: dpjxh4jhr63k2

![image](https://user-images.githubusercontent.com/42587159/108115594-5e1e2e00-70c0-11eb-8701-80be4bb80e9d.png)

**Comment by gilvaju** [comment] 2021-03-09 12:16
I have the same issue here

![image](https://user-images.githubusercontent.com/677039/110469034-df615300-80b7-11eb-935a-27263676dca3.png)

![image](https://user-images.githubusercontent.com/677039/110469077-eee09c00-80b7-11eb-9c32-2844424db57c.png)

I can't delete any app on admin panel. I already delete the entire stack and I still can't delete the apps

**Comment by cnbrkkaya** [comment] 2021-06-03 07:08
I have the same problem. 
Is there any progress?

**Comment by Pablion** [comment] 2021-09-19 12:41
I have the same problem.
Is there any progress?

**Comment by ganipcanot** [comment] 2021-11-10 22:57
Have you tried the suggestion here: https://github.com/aws-amplify/amplify-console/issues/1330

Specifically: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

**Comment by michaelbrewer** [comment] 2021-12-03 02:13
@ganipcanot - this fixes it for me, but the AWS console should also do this

**Comment by Narrator** [comment] 2021-12-06 19:15
@apiel51 @marlonmarcello @sharmaaditya570191 @gilvaju @cnbrkkaya @PabloLION 

Could any of you please confirm if you attempted to delete the backends via CloudFormation first before attempting a delete via the AWS Console? Also, have you tried the workaround suggested here: [#1330 (comment)](https://github.com/aws-amplify/amplify-console/issues/1330#issuecomment-739493860) and did that resolve your issue?

We are currently unable to reproduce the issue correctly. I would really appreciate if any of you could provide detailed reproduction steps, so I can investigate this properly.

**Comment by michaelbrewer** [comment] 2021-12-06 19:38
@Narrator - yes, this is what happened to mine. Using the aws cli seems to fix it.

**Comment by smoothness** [comment] 2021-12-26 14:45
Having the same problem for almost 2 months,  so annoying.

**Comment by ocbrollingpaper** [comment] 2021-12-31 18:52
> Having the same problem for almost 2 months, there is no trace left of any resource that backs the Amplify projects anymore, no CloudFormation, no nothing, how it is possible that no one can fix this... so annoying.

Same

**Comment by danielqba** [comment] 2022-02-05 04:22
no progress? same problem here!

**Comment by ZachMurray** [comment] 2022-12-14 17:01
> Have you tried the suggestion here: [#1330 (comment)](https://github.com/aws-amplify/amplify-hosting/issues/1330#issuecomment-739493860)
> 
> Specifically: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

Thanks Ganipcanot, you're a true hero.

**Comment by ZachMurray** [comment] 2022-12-14 17:04
This is what worked for me. 

> open AWS CloudShell and run cmd: aws amplify delete-app --app-id <your_app-id>
> you can find amplify app id at amplify app detail

Credit due: 
https://stackoverflow.com/a/70894285/11705601

**Comment by swaminator** [comment] 2024-03-20 20:14
We have since fixed this issue. Resolving.

**Closed by swaminator** 2024-03-20 20:14 UTC
Labels: bug, pending-prioritization, backend-builds
