### ISSUE TITLE
Custom domain is serving old builds, Amplify builds are creating new CloudFront distrubtions

### ISSUE THREAD

**Issue by dansokol** [aws-amplify/amplify-hosting#2987] opened 2022-09-15 16:26 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2lw9gp91e6yf1

### Region

us-east-2

### Amplify Hosting feature

Not applicable

### Describe the bug

After doing a new successful build/deploy with Amplify, my custom domain is still serving the old build.  This started happening recently, everything was working fine until a few days ago.  Also noticed that under the "Deploy" tab it is creating a new cloudfront distribution rather than updating the existing one (which it previously used to do).

### Expected behavior

After a new build, custom domain should serve the latest version.

### Reproduction steps

1. Run a build/deployment with Amplify
2. Browse to custom domain and it shows old build compared to master...amplifyapp.com build

**Comment by jag-ermeister** [comment] 2022-09-20 00:19
We just saw the same thing today.

**App Id**
d1meccdtkyp4ol

**Region**
us-east-1

We repeatedly pushed, re-pushed, etc., and we kept getting back the old build.  Interestingly, we then went to `App Settings > Domain Management > Manage subdomains` and tweaked with some settings on that page (for an unrelated subdomain and an unrelated branch).  Upon hitting `Update`, that inexplicably caused things to start working.  It seems that it somehow triggered a process that finally caused our domain to serve the new files.

**Comment by aungbobotun** [comment] 2022-09-20 11:05
Faced the same issue in the US region since Sep13, and the Singapore region since Sep 20. Is AWS team sleeping?

**Comment by aungbobotun** [comment] 2022-09-20 11:10
This issue is serious. Plz we are also facing the issue. At least reply on this. @palpatim  @mauerbac @manueliglesias

**Comment by ramachandra-sahu** [comment] 2022-09-20 12:39
I am also facing the same issue in ap-southeast-1(Singapore) region since 20-Sep-22. Could you please let us know the solution.

@palpatim @mauerbac @manueliglesias

**Comment by multivoltage** [comment] 2022-09-20 16:51
Same issue eu-west-1

**Comment by arundna** [comment] 2022-09-20 17:23
@multivoltage @ramachandra-sahu @JFDontigny - We're actively looking into this issue and keep you posted with an update.

**Comment by multivoltage** [comment] 2022-09-20 17:27
Thanks for support

**Comment by hloriana** [comment] 2022-09-20 20:52
@multivoltage @ramachandra-sahu @JFDontigny @aungbobotun @dansokol  Apologies for this inconvenience. New deployments of your app should no longer create new SSR resources in your account (CloudFront distribution, Lambda@Edge functions, S3 buckets). The resources created with your last deployment will be used for future builds. 

If you are using custom domains, we are actively working on a solution for having your custom domains serve the latest content. We are treating this with high priority and we'll keep you posted with an update.

Thank you all for your patience.

**Comment by croossin** [comment] 2022-09-21 01:41
We are also seeing this issue relating to custom domains. Please bump urgency.

**Comment by Sherdycoder** [comment] 2022-09-21 02:01
Adding and then removing an additional subdomain resolved the issue for us, but its unclear if we'll need to repeat after our next build.

**Comment by multivoltage** [comment] 2022-09-21 16:32
In this moment I have the problem only for branch production.  Staging in my case has got the problem.
Reading logs of deploy it seems that now Amplify did not create new istances (lambda, s3, etc) every build, but re-use (as expected) the old one. But the the problem persists

**Comment by hloriana** [comment] 2022-09-21 16:40
For anyone still running into the custom domains issue please follow these steps to ensure your custom domain is serving the latest content:

- In the Amplify Console, navigate to App settings -> Domain management
- Select the Manage subdomains button -> NO NEED TO MAKE ANY CHANGES to this section
- Click on the Update button

Once the domain update process has completed, navigate to your custom domains in the browser and they should now serve the latest content.

**Comment by hloriana** [comment] 2022-09-21 20:53
We are closing this issue as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2982. Please refer to that issue for any further updates. Thank you!

**Closed by hloriana** 2022-09-21 20:53 UTC
Labels: custom-domain
