### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN issue

### ISSUE THREAD

**Issue by anaji** [aws-amplify/amplify-hosting#2125] opened 2021-08-02 12:00 UTC
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3f9mt4lztg5ah

### Region

eu-west-1

### Step

Domain Activation

### Status

Success

### Issue or question

After the domain activation succeed, impossible to access to the website, the following error is shown:
DNS_PROBE_FINISHED_NXDOMAIN

### Error message

DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Jay2113** [comment] 2023-06-28 20:47
Hi @anaji 👋 , thank you for reaching out to us and we apologize for the delayed response on the thread.

I observed that your Amplify app `d3f9mt4lztg5ah` has a custom domain (orbiticons.com) associated to it. Additionally, the custom domain has been successfully activated and it seems to be resolving as expected.

That being said, if the issue resurfaces I would highly recommend reviewing this [article](https://repost.aws/knowledge-center/route-53-troubleshoot-nxdomain-responses) which outlines some potential root causes of the `DNS_PROBE_FINISHED_NXDOMAIN` error. 

I am going to close this thread since the issue seems to have been resolved but please feel free to open a new GitHub issue if you are experiencing issues with Amplify Hosting.

**Closed by Jay2113** 2023-06-28 20:47 UTC
Labels: bug, custom-domain
