### ISSUE TITLE
404 page does not exist

### ISSUE THREAD

**Issue by otaku0304** [aws-amplify/amplify-hosting#3018] opened 2022-10-04 05:35 UTC
After the successful deploy of build the webpage is working good, but the problem is when I try to  change the page it is showing  404 error.

**Provide additional details**

version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist/retur-nation-fe
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

**What AWS Services are you utilizing?**

AWS Amplify

**Provide additional details e.g. code snippets**

![404](https://user-images.githubusercontent.com/107242846/193742222-332c53a8-d3a1-4c0e-87cb-617088fea254.png)

**Comment by hloriana** [comment] 2022-10-04 20:45
Hi @otaku0304 thanks for raising this issue. We need some more details in order for us to troubleshoot this issue. Please either fill out the [Bug Report template](https://github.com/aws-amplify/amplify-hosting/issues/new?assignees=&labels=&template=1.bug_report.yaml) or respond with your App ID and region.

**Comment by hloriana** [comment] 2022-10-04 22:56
Looking at your screenshot and `baseDirectory` setting, it appears you are using localization with an Angular application which Amplify Hosting does not support at this time. Apologies for the inconvenience. Closing as a duplicate of #3016

**Closed by hloriana** 2022-10-04 22:56 UTC
Labels: question, hosting
