### ISSUE TITLE
Next.js build error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"

### ISSUE THREAD

**Issue by dstout-current** [aws-amplify/amplify-hosting#3460] opened 2023-05-04 18:55 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2gggx07fsqlf1

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Describe the bug

Suddenly new builds are failing with this error in the Frontend build logs:

```
2023-05-04T18:43:15.534Z [INFO]: Starting SSR Build...
2023-05-04T18:45:09.634Z [ERROR]: Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"
                                  at NextjsComponent.validatePathPatterns (/root/./-patch.2/node_modules/@sls-next/-component/dist/component.js:97:19)
                                  at NextjsComponent.<anonymous> (/root/./-patch.2/node_modules/@sls-next/-component/dist/component.js:346:18)
                                  at Generator.next (<anonymous>)
                                  at fulfilled (/root/./-patch.2/node_modules/@sls-next/-component/dist/component.js:5:58)
                                  at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-05-04T18:45:09.636Z [ERROR]: [G[?25h[G[J
                                  74s › d2gggx07fsqlf1 › Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"
```

I reverted to an old commit and pushed that with no changes, and that new build also failed, even though it had originally succeeded.

### Expected behavior

This error should not occur.

### Reproduction steps

The version of `next` in package.json is "12.3.4"

The app in Amplify is still using the "Web dynamic" platform because "Web Compute" caused other errors.

### Build Settings

```yaml
amplify.yml uncustomized
```

### Log output

<details>

```
2023-05-04T18:43:15.534Z [INFO]: Starting SSR Build...
2023-05-04T18:45:09.634Z [ERROR]: Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"
                                  at NextjsComponent.validatePathPatterns (/root/./-patch.2/node_modules/@sls-next/-component/dist/component.js:97:19)
                                  at NextjsComponent.<anonymous> (/root/./-patch.2/node_modules/@sls-next/-component/dist/component.js:346:18)
                                  at Generator.next (<anonymous>)
                                  at fulfilled (/root/./-patch.2/node_modules/@sls-next/-component/dist/component.js:5:58)
                                  at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-05-04T18:45:09.636Z [ERROR]: [G[?25h[G[J
                                  74s › d2gggx07fsqlf1 › Error: CloudFront input failed validation. Could not find next.js pages for "_next/image*"

```

</details>

**Comment by hloriii** [comment] 2023-05-25 19:41
Hi @dstout-current apologies for the delay here but it looks like your most recent builds has been successful. Were able to find the cause of the issue? Also, you mentioned migrating to WEB_COMPUTE resulted in some errors. What errors were you running into?

**Comment by DanielStout5** [comment] 2023-05-26 17:38
This particular error seemingly went away on its own the next day without any changes.

We had several issues with WEB_COMPUTE - calls to Next APIs stopped working (returned 503 cloudflare error) and dynamic pages (e.g. pages/[postid].js) weren't getting included in the build,

Downgrading back to web dynamic fixed those issues

**Comment by dstout-current** [comment] 2023-05-26 17:52
This particular error seemingly went away on its own the next day without any changes.

We had several issues with WEB_COMPUTE - calls to Next APIs stopped working (returned 503 cloudflare error) and dynamic pages (e.g. pages/[postid].js) weren't getting included in the build (would return 404).

Downgrading back to web dynamic fixed those issues

**Comment by Jay2113** [comment] 2024-02-14 01:49
I am going to close this thread as the original issue is resolved. Also, reviewed the latest build (67) on the `main` branch and it has deployed successfully.

**Closed by Jay2113** 2024-02-14 01:49 UTC
Labels: question, compute
