### ISSUE TITLE
Deployment periodically gets stuck at "Failed to deploy".

### ISSUE THREAD

**Issue by johnenderson** [aws-amplify/amplify-hosting#3638] opened 2023-08-09 19:15 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

dzy01yjm2a62s

### AWS Region

us-east-1

### Amplify Hosting feature

Deployments

### Question

Deployment periodically gets stuck at "Failed to deploy".

It happened today:

2023-08-09T18:41:44 [INFO]: Updating Edge config
2023-08-09T18:41:45 [ERROR]: Failed to deploy

Manual deployments by uploading a file directly work without issues. I tried restarting a few times and waited for a few hours, but nothing happens.

`APP_ID_AMPLIFY: "dzy01yjm2a62s"`
`REGION: us-east-1`

**Comment by johnenderson** [comment] 2023-08-10 11:44
when performing manual deployment succeeding

2023-08-10T11:43:35 [INFO]: Starting Deployment
2023-08-10T11:43:35 [INFO]: Updating Edge config
023-08-10T11:43:35 [INFO]: Beginning deployment for application dzy01yjm2a62s, branch:eng-197-2-2-0, buildId 0000000012
2023-08-10T11:43:35 [INFO]: Got archive: 25283872 bytes
2023-08-10T11:43:46 [INFO]: Deployment complete

**Comment by johnenderson** [comment] 2023-08-10 15:00
Amazon account # 938552245792
I'm not on the free tier

**Comment by Jay2113** [comment] 2023-08-10 19:49
Discussed with @johnenderson on our community discord server that the root cause of the issue is related to the use of `source-url` method of performing manual deployments via the AWS CLI using `start-deployment` API/CLI:
```
aws amplify start-deployment --app-id $APP_ID_AMPLIFY --branch-name $BRANCH_NAME --source-url $S3_PRESIGN_URL
```
We are already tracking this as a bug here: https://github.com/aws-amplify/amplify-hosting/issues/3500

Our recommendation would be to either upload the build artifacts via the zip file or use the Amazon S3 method to deploy the app.

Closing this thread to keep all the communication for this bug in the same place: https://github.com/aws-amplify/amplify-hosting/issues/3500

**Closed by Jay2113** 2023-08-10 19:49 UTC
Labels: question, manual-deploy
