### ISSUE TITLE
Updates not deployed with web compute platform/Next.js 12

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-hosting#3213] opened 2022-12-22 04:40 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed sensitive information from my code snippets and submission.

### App Id

dtdpgqv8ojaum

### AWS Region

us-east-2

### Amplify Hosting feature

Deployments, Monorepo

### Describe the bug

After updating the application to use the new web compute, changes are not deployed. The build is booming, and all steps are complete, including deploy; there are just no changes. Reverting to WEB_DYNAMIC and redeploying the branch works as expected.

### Expected behavior

Changes are deployed

### Reproduction steps

Deploy a next.js monorepo to compute the platform

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

Does monorepo usage possibly cause it?

**Comment by daxiang28** [comment] 2023-01-09 21:56
I recall I had to remove the root redirects when I migrated to web_compute b/c. Were you able to get this resolved?

**Comment by Nimzyow** [comment] 2023-01-10 18:28
I can confirm we had the same experience as the original poster.

We ran the command to revert to the old WEB_DYNAMIC configuration which does revert but we have a new problem. Each deployment now overrides the behaviours in our CloudFront distribution and also removes the _next/image behaviour, which is extremely problematic for us as we have a second custom origin. To be clear, our CloudFront behaviours were not being overridden on deployments before this migration.

At this stage, we cannot deploy anything into our staging or production branches as this will break our site. 

If anyone else has had any luck on resolving this, we would greatly appreciate any feedback.

**Comment by drmzio** [comment] 2023-01-10 21:10
Also having this issue when migrating to WEB_COMPUTE and deployment changes aren't reflected, even though deployment was successful. Why is this happening?

**Comment by treewhopper** [comment] 2023-01-12 13:09
It's not just you, there is an issue with Next.js bundle deployment for WEB_COMPUTE.

I have this in writing from AWS support:

"I have received update from internal team and they acknowledged the issue as known issue with Next.js bundle deployment. The team have plans to address this issue and unfortunately we dont have any timeline on the resolution."

**Comment by treewhopper** [comment] 2023-01-12 13:31
Probably a dupe of #3131

**Comment by tim-vyg** [comment] 2023-04-05 23:03
+1 on this issue - after migrating to WEB_COMPUTE, deployment changes aren't reflected, even though deployment was successful. But reverting back to WEB_DYNAMIC works

**Comment by Jay2113** [comment] 2024-02-22 18:35
👋 , this thread seems to be a duplicate of #3131. As stated here https://github.com/aws-amplify/amplify-hosting/issues/3131#issuecomment-1546410324, this issue has been fixed. Closing.

**Closed by Jay2113** 2024-02-22 18:35 UTC
Labels: bug, pending-triage, compute
