### ISSUE TITLE
git-lfs installation

### ISSUE THREAD

**Issue by user1825** [aws-amplify/amplify-hosting#3486] opened 2023-05-19 15:58 UTC
### Before opening, please confirm:

- [x] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

arn:aws:amplify:ca-central-1:099447840701:apps/d3fmd1d190w9co

### AWS Region

ca-central-1

### Amplify Hosting feature

Frontend builds

### Question

Hello,

I have recently started using aws amplify, the frontend of my app is hosted on aws amplify.  I've been using git lfs to add some videos in my app, my app has been hosted for around 2 months now, and then 2 days ago when i made a new build(nothing related to git-lfs), my git-lfs installation started throwing this 

> error:No package git-lfs available.

Below you can find my amplify.yml file.

`version: 1`
`frontend:`
` phases:`
`    preBuild:`
`       commands:`
`        - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash`
`        - yum install git-lfs`
`        - git-lfs install`
`        - git-lfs pull`
`        - npm install --force`
`    build:`
`      commands:`
`        - npm run build`
`  artifacts:`
`    baseDirectory: build`
`    files:`
`      - '**/*'`
`  cache:`
`    paths:`
`      - node_modules/**`
`  env:`
`    variables:`
`      GIT_LFS_ENABLED: "true"`
`buildSpec:`
`  amplify:`
`    phases:`
`      build:`
`        commands:`
`          - echo "Build completed on Amplify build server"`

I don't understand why it's throwing this error as everything was fine from a long time and through so many builds, I know i can use S3 rather than lfs or use a docker image but I would like to know what went wrong here?

Thanks for your help!

**Comment by Jay2113** [comment] 2023-06-08 18:24
Hi @user1825 👋 , thanks for reaching out to us and apologies for the delayed response on this thread.

After reviewing your build logs from May 19, it seems that the builds started failing due to the missing `git-lfs` package and the root cause seems related to how the `git-lfs` package was being installed:

```
- curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
- yum install git-lfs
``` 

I observed that your subsequent builds succeeded when the `git-lfs` package was installed using the binary package from [here](https://github.com/git-lfs/git-lfs#from-binary).

I am going to close this thread since the issue seems to have been resolved but please feel free to open a new GitHub issue if you are experiencing issues with Amplify Hosting.

**Closed by Jay2113** 2023-06-08 18:24 UTC
Labels: question, frontend-builds
