### ISSUE TITLE
Can't delete my Amplify App

### ISSUE THREAD

**Issue by jigr-web-services** [aws-amplify/amplify-hosting#2887] opened 2022-07-26 13:57 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d26h9qcsu15zer

### Region

us-west-2

### Amplify Hosting feature

Not applicable

### Describe the bug

I want to delete this App from my Amplify console. But everytime I do, I get this error: 

```
Delete app d26h9qcsu15zer failed with reason: ResourceNotFoundException - An error occurred while processing your request: S3 bucket amplify-jigrpkurlshortner-dev-153559-deployment or object #current-cloud-backend.zip was not found
```

I had accidentally deleted the bucket it mentions. But now I am stuck with it... 

### Expected behavior

Delete the Amplify app

### Reproduction steps

1. Login to AWS Console
2. Go to AWS Amplify
3. Go to All Apps, and click the App thumbnail I want to delete
4. Click "Delete App" under the top right "Actions" menu

**Comment by hloriana** [comment] 2022-07-26 19:07
Hi @jigr-web-services can you try running:
 `aws amplify delete-backend-environment --app-id <appID> --environment-name <backend env name>`

After this you can go back into the console and delete the app again.

Please let us know if this is not successful.

**Comment by jigr-web-services** [comment] 2022-07-27 07:28
Thanks @hloriana. I tried to try this command on CloudShell. I get this `Unable to start the environment. To retry, refresh the browser or restart by selecting Actions, Restart AWS CloudShell. System error: Environment was in state: CREATION_FAILED. Expected environment to be in state: RUNNING. To retry, refresh the browser or restart by selecting Actions, Restart AWS CloudShell.`  Then I also tried to restart the CloudShell, no luck. I also deleted CloudShell home directory and tried again, no luck either. 

Not sure what's wrong with the account. Now I'll try on AWS CLI on my machine.

**Comment by jigr-web-services** [comment] 2022-07-27 12:32
I tried using aws CLI v2  and it worked. I used `aws amplify delete-app --app-id <app-id>  --profile <aws-profie>`. I had to assign `AdministratorAccess-Amplify` and a custom policy to IAM user for aws profile.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "amplify:DeleteApp",
            "Resource": "*"
        }
    ]
}
```

**Comment by hloriana** [comment] 2022-07-27 20:54
Awesome! We are already tracking this bug in our product backlog. 

Closing as duplicate of: https://github.com/aws-amplify/amplify-hosting/issues/2548. Feel free to track progress for the bug fix on that issue.

**Closed by hloriana** 2022-07-27 20:54 UTC
Labels: question, console

**Comment by johnpc** [comment] 2022-09-27 01:03
When deleting via Amplify console, the error reported

```
Delete app d26h9qcsu15zer failed with reason: ResourceNotFoundException - An error occurred while processing your request: S3 bucket amplify-jigrpkurlshortner-dev-153559-deployment or object #current-cloud-backend.zip was not found
```

has been fixed. you should be able to re-try deleting your app from Amplify console.
