### ISSUE TITLE
Unable to build my project after updating my package.json - The size of the build output exceeds the max allowed size 

### ISSUE THREAD

**Issue by giovannetti-eric** [aws-amplify/amplify-hosting#3628] opened 2023-07-29 02:19 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1amztsbwwd9h9

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Frontend framework

Next.js

### Next.js version

13.4.12

### Next.js router

Pages Router

### Describe the bug

Updated my package.json and got his error during the build:

2023-07-29T02:10:38.605Z [ERROR]: !!! CustomerError: The size of the build output (324350330) exceeds the max allowed size of230686720 bytes. Please reduce the size ofyour build output and try again.

This is the packages updated with `npm update`, before and after:

```shell
Package                                Current      Wanted
@emotion/react                         11.10.6     11.11.1
@emotion/styled                        11.10.6     11.11.0
@fortawesome/fontawesome-svg-core        6.3.0       6.4.0
@fortawesome/free-brands-svg-icons       6.3.0       6.4.0
@fortawesome/free-solid-svg-icons        6.3.0       6.4.0
@fortawesome/pro-duotone-svg-icons       6.3.0       6.4.0
@fortawesome/pro-light-svg-icons         6.3.0       6.4.0
@fortawesome/pro-regular-svg-icons       6.3.0       6.4.0
@fortawesome/pro-solid-svg-icons         6.3.0       6.4.0
@headlessui/react                       1.7.13      1.7.13
@mui/material                          5.11.12      5.14.2
@next/bundle-analyzer                   13.2.4     13.4.12
@playwright/test                        1.31.2      1.36.2
@sentry/nextjs                          7.42.0      7.60.1
@storybook/addon-essentials              7.0.5       7.1.1
@storybook/addon-interactions            7.0.5       7.1.1
@storybook/addon-links                   7.0.5       7.1.1
@storybook/addon-mdx-gfm                 7.0.5       7.1.1
@storybook/blocks                        7.0.5       7.1.1
@storybook/nextjs                        7.0.5       7.1.1
@storybook/react                         7.0.5       7.1.1
@storybook/testing-library               0.1.0       0.1.0
@stripe/react-stripe-js                  2.1.0       2.1.1
@stripe/stripe-js                       1.52.0      1.54.1
@tailwindcss/forms                       0.5.3       0.5.4
@testing-library/jest-dom               5.16.5      5.17.0
@typescript-eslint/eslint-plugin        5.54.1      5.62.0
@typescript-eslint/parser               5.54.1      5.62.0
axios                                    1.3.4       1.4.0
chromatic                               6.17.1      6.20.0
clsx                                     1.2.1       1.2.1
cssnano                                 5.1.15      5.1.15
date-fns                                2.29.3      2.30.0
embla-carousel-react                8.0.0-rc07  8.0.0-rc11
eslint                                  8.36.0      8.46.0
eslint-config-next                      13.2.4     13.4.12
eslint-config-prettier                   8.7.0       8.9.0
eslint-plugin-prettier                   4.2.1       4.2.1
eslint-plugin-storybook                 0.6.11      0.6.13
firebase                                9.17.2      9.23.0
formik                                   2.2.9       2.4.2
glob                                     9.2.1       9.3.5
jest                                    29.5.0      29.6.2
jest-environment-jsdom                  29.5.0      29.6.2
msw                                      1.2.1       1.2.3
next                                    13.2.4     13.4.12
next-sitemap                             4.0.5       4.1.8
postcss                                 8.4.21      8.4.27
postcss-nesting                         11.2.1      11.3.0
prettier                                 2.8.4       2.8.8
prettier-plugin-tailwindcss              0.2.4       0.2.8
pusher-js                                8.0.1       8.3.0
react-cropper                            2.3.1       2.3.3
react-webcam                             7.0.1       7.1.1
sass                                    1.59.2      1.64.1
sharp                                   0.31.3      0.31.3
storybook                                7.0.5       7.1.1
stripe                                 11.17.0     11.18.0
swr                                      2.1.0       2.2.0
tailwind-merge                          1.10.0      1.14.0
tailwindcss                              3.2.7       3.3.3
typescript                               4.9.5       4.9.5
yup                                      1.0.2       1.2.0
``` 

### Expected behavior

Being able to deploy my project

### Reproduction steps

N/A

**Comment by Jay2113** [comment] 2023-08-04 17:43
Hi @giovannetti-eric 👋 , thanks for raising this with us and apologies for the delayed response on this thread.

The root cause of the deployment error `The size of the build output exceeds the max allowed size` is as follows:
- Previously, Amplify Hosting used to build your app using the Next.js `standalone` mode as part of its bundling strategy. We just released some changes to improve how we bundle Next.js apps. These changes don't need the `standalone` directory anymore. That should help eliminate the problem of reaching the 200MB bundle limit. However, these changes require a new deploy in your application to take effect.
- Secondly, you can still exceed the bundle limit if you have a large amount of images and/or video files in your `public` directory. Our recommendation would be to store these assets in Amazon S3 and serve them from there.

Lastly, it seems that the latest builds on your `rc` branch have succeeded. I am going to close this thread but please feel free to open a new issue if you are experiencing any issues with Amplify Hosting.

**Closed by Jay2113** 2023-08-04 17:43 UTC
Labels: investigating, compute
