### ISSUE TITLE
Changing Access control has no affect

### ISSUE THREAD

**Issue by NotLuksus** [aws-amplify/amplify-hosting#2695] opened 2022-04-11 12:36 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3i7o7urelozvr/settings/access

### Region

eu-central-1

### Amplify Hosting feature

Access control

### Describe the bug

When I change the access control for my apps it doesn't actually effect the page, it still shows the password login screen. I also tried changing the password, but the password stays as before, so it isn't effected either.

### Expected behavior

Access Control should be changed to public / the password should be changeable

### Reproduction steps

1. Click on Manage access
2. Select "Publically viewable" from the access setting drop down
3. Click Save

1. Click on Manage access
2. Enter a new password in the password field
3. Confirm the password by entering it again in the corresponding field
4. Clicking save

**Comment by hloriana** [comment] 2022-05-04 16:02
Hi @NotLuksus 👋🏽 I was able to reproduce this bug. We have added this to our backlog for prioritization and will respond as soon as this is fixed.

**Comment by hloriana** [comment] 2022-05-04 16:06
I was able to work around this by creating a new password for a new user.

**Comment by hloriana** [comment] 2022-05-04 16:55
Closing since this original bug was resolved. The bug I found will be tracked separately. If you are still experiencing issues with disabling, enabling, or changing passwords for access control please re-open.

**Closed by hloriana** 2022-05-04 16:55 UTC
Labels: bug, access control
