### ISSUE TITLE
isBot and userAgent still do not work in Next.js middleware.ts

### ISSUE THREAD

**Issue by bc-ptg** [aws-amplify/amplify-hosting#3202] opened 2022-12-14 15:41 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d1t9rp4d0o2r64

### AWS Region

us-east-1

### Amplify Hosting feature

SSR

### Describe the bug

We are still having trouble with the issue described in https://github.com/aws-amplify/amplify-hosting/issues/3159

Apologies for the separate ticket, as I don't see a way to reopen or comment on the original.

There is some talk on forwarding the client request headers to the app, but I don't see any way to do this outlined in the documentation. We also set up a vanilla Next 13 app to rule out anything in our own app that may be causing the issue but we are still experiencing it.

Original issue as follows:

`userAgent(request)` called within `middleware.ts` does not behave as expected.

In particular `isBot` always returns false.

Example middleware.ts as follows:

```
import { NextRequest, NextResponse, userAgent } from 'next/server';

export function middleware(request: NextRequest) {
    const { isBot, browser, device, engine } = userAgent(request);

    if (isBot) {
        return NextResponse.redirect("https://this-is-a-bot");
    } else {
        return NextResponse.redirect("https://this-is-not-a-bot");
    }

}
```

We also noticed the browser, device, and engine responses also never appear to return any data, although our primary concern is isBot as we need that to implement rewrites for prerender.io.

### Expected behavior

After changing the browser's user agent to a bot's, such as `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)` and implementing the example middleware.ts, visiting the app should redirect to the "this-is-a-bot" result. This works when building and testing locally, however on Amplify it always redirects to the "this-is-not-a-bot" result.

### Reproduction steps

1.     Implement the example middleware.ts and push to Amplify
2.     Change your browser's useragent to a bot's, e.g. `Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)`
3.     Visit the app and observe the incorrect return from middleware.ts

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by hloriana** [comment] 2022-12-16 18:50
Hi @bc-ptg 👋🏽 thanks for raising this issue. I was able to reproduce this behavior. It's important to note that Amplify runs Next.js middleware after the CDN cache. So middleware may not necessarily run on every request. 

Additionally, the `user-agent` header is replaced with a value of `"Amazon CloudFront"`, this is because we don't make the user-agent part of the cache key in the interest of increasing your cache hit ratio, otherwise, given the cardinality of this header, you would experience a very low cache hit ratio, which is undesirable. 

Since Next.js `isBot` detection relies on the userAgent value, I think that's the reason why it is always false. I will pass along this to our product management team to make sure we document this behavior better.

**Comment by hloriana** [comment] 2023-02-22 16:15
Closing this issue since this is a not a bug and is intended behavior with the `user-agent` header.

**Closed by hloriana** 2023-02-22 16:15 UTC
Labels: question, investigating, compute
