### ISSUE TITLE
Hosting backend build shows a warning on Apps limit reached 

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-hosting#2797] opened 2022-06-09 14:40 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1sssy1xajmiw6

### Region

us-east-1

### Amplify Hosting feature

Backend builds

### Describe the bug

Currently, observing the following warning message:

`⚠️ The maximum number of apps that you can create with Amplify in this region has likely been reached: For more information on Amplify Service Quotas, see: https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify`

The region currently only has 7 Amplify Apps deployed.

### Expected behavior

The warning can be misleading to customers. 

### Reproduction steps

observe the backend logs to the end

**Comment by rafaelfaria** [comment] 2022-08-06 02:59
I get the same message and I only have 1 app.

**Comment by phoenixbeats01** [comment] 2022-08-14 19:19
Getting this message too

**Comment by TimRoadley** [comment] 2022-08-17 00:55
Getting this message too, only have 1 amplify app and quote of 25

**Comment by trsrm** [comment] 2022-08-18 20:44
+1

**Comment by lysna87** [comment] 2022-09-15 06:50
I also have this on my second branch of my only app. App redeploys every time I update gitHub, and this is my seventh deployment on this branch.

**Comment by shgamedev** [comment] 2022-09-21 12:43
+1 on this. Only one Amplify app in 1 region across the entire AWS account.

**Comment by dmiller1006** [comment] 2022-09-21 13:27
+1 on this. Only one Amplify app in 1 region across the entire AWS account.

**Comment by ogg130** [comment] 2023-01-22 00:16
+1 - just saw the same, doesnt appear to be causing any problems for me however

**Comment by tlb-jason** [comment] 2023-02-06 06:13
+1 same warning. 1 app / 1 previously deleted

**Comment by weisisheng** [comment] 2023-04-15 05:55
+1, me as well. 11 apps. upgraded limits a few weeks ago to 40.

**Comment by Aladdinsmahome** [comment] 2023-04-18 10:58
+1 same warning.

**Comment by rafanami** [comment] 2023-04-20 23:26
+1, same warning

**Comment by cfjohan** [comment] 2023-04-25 09:42
I'm seeing this too, except for me it's not a warning but an error message that's stopping me from deploying more than one app in the same account. Region is eu-north-1.

**Comment by anibal21** [comment] 2023-04-28 04:52
+1, same error, and if I try to create with cli says this: An error occurred (LimitExceededException) when calling the CreateApp operation (reached max retries: 2): Failed to create app. You have reached the maximum number of apps in this account.

**Comment by conormb** [comment] 2023-04-28 17:16
+1 same error.  Does not appear to effect the actual output.

**Comment by MykolaRehedaDev** [comment] 2023-05-01 13:40
Have only 1 app but have error:
"You have reached the Amplify App limit for this account and region"

**Comment by timhradil** [comment] 2023-05-02 01:22
+1 I am getting this as well

**Comment by jaime-skupee** [comment] 2023-05-02 16:26
+1 I'm also facing the same issue

I got the limit on 7, I delete one, I have currently 6 apps and even though I have the message "Failed to create app. You have reached the maximum number of apps in this account."

**Comment by BrianHHough** [comment] 2023-05-08 03:02
In the docs page that @ykethan shared above, there is an `Adjustable` column, and the # of apps has a `Yes` button with an arrow for that value. If you click on that, it will redirect you to a page in your AWS Management Console that looks like this:

![Screenshot 2023-05-07 at 10 59 54 PM](https://user-images.githubusercontent.com/56947075/236724332-3e51b4ef-6bc3-4d86-a2fe-77f8a9f9f36d.png)

If you try to request a limit increase to the # of apps in your account, this might be worth a shot to correct the issue. Seems like there might be a behind-the-scenes quote limit for apps deployed via the AWS Amplify service, so requesting a limit increase might correct this issue.

**Comment by nayan32biswas** [comment] 2023-05-19 09:32
Getting same message, only have 2 amplify app out of app quote 25.

**Comment by osmanelsoz** [comment] 2023-05-20 18:58
Same error, 1 currently active 1 deleted app.

**Comment by Neon-20** [comment] 2023-05-21 19:11
Is there any possibility of this clearing out guys?
Is there any solution to the problem of 
Limit of apps hosted.... :(

**Comment by yegenpres** [comment] 2023-05-24 12:15
the same problem, I did not have any app.

**Comment by JelsB** [comment] 2023-05-25 19:56
Same here. I had one app already. A new app's `amplify init` resulted in an error
> You have reached the Amplify App limit for this account and region.

After deleting the already existing app, the new app's `amplify init` was successful. No idea why that worked though.

**Comment by hippymitty** [comment] 2023-06-17 05:17
I'm also getting this issue. I have one app deployed and trying to deploy another, I deleted one too not that long ago. My quota shows as 25

**Comment by Omphemetse-methods** [comment] 2023-06-25 23:25
> I'm also getting this issue. I have one app deployed and trying to deploy another, I deleted one too not that long ago. My quota shows as 25 Edit - I was using ap-southeast-2. I have changed to southeast-1 and am able to deploy

Changing the region also worked for me.

**Comment by renoevolution** [comment] 2023-07-07 21:48
I'm getting the same error. I have just one configured

**Comment by drscrolls** [comment] 2023-07-16 08:10
Had the same issue. This was the fix that worked https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/select-region.html

**Comment by santiagocezar** [comment] 2023-07-18 01:21
+1 because there's not much else I can do, other than bumping this issue. Already tried deleting another app, I'm waiting for the quota request to be resolved

**Comment by santiagocezar** [comment] 2023-07-22 21:11
My limit increase request got approved, which fixed it. No idea why that did work but deleting an app didn't.

**Comment by brunopinna** [comment] 2023-07-26 09:13
+1 I just have one app, adding the second one triggers the error, even though the quota is 25.

**Comment by dacarva** [comment] 2023-07-26 23:49
Same issue here. Only one app and I can't add another one

**Comment by gpowell1** [comment] 2023-08-07 14:45
I have the same issue, had previous apps that I deleted to make room and still can't add app.

**Comment by brunopinna** [comment] 2023-08-07 17:26
Hi there,Thank you very much for the workaround. Unfortunately, I would not expect this kind of issues from AWS services so I already closed my AWS account.    ---- On Mon, 07 Aug 2023 18:06:13 +0100  ***@***.***> wrote ----  
One solution /work around build an App in a region you haven't used before. If you need to get building in a hurry.

**Comment by Salman-Sali** [comment] 2023-09-19 11:55
I had 10 apps and quota of 25. But when I deleted 1 app, I was able to create new one.

**Comment by theyashmhatre** [comment] 2023-09-30 18:02
Hi All. I too had the same issue. Mine was a fairly new account. Only 1 or 2 months.
AWS team advised me to create and run an EC2 container for a minimum of 24 hours. And that solved the issue

**Comment by bgavas** [comment] 2023-11-23 17:47
I had the same issue. Using another region fixed my issue. But I feel like this is a temporary solution.

**Comment by georgevicbell** [comment] 2023-12-09 12:25
I'm getting this as well...I have 10 apps running in one region, but that is it...

**Comment by StanislavStadnyk** [comment] 2024-01-31 23:16
> In the docs page that @ykethan shared above (https://docs.aws.amazon.com/general/latest/gr/amplify.html#service-quotas-amplify), there is an `Adjustable` column, and the # of apps has a `Yes` button with an arrow for that value. If you click on that, it will redirect you to a page in your AWS Management Console that looks like this:
> 
> ![Screenshot 2023-05-07 at 10 59 54 PM](https://user-images.githubusercontent.com/56947075/236724332-3e51b4ef-6bc3-4d86-a2fe-77f8a9f9f36d.png)
> 
> If you try to request a limit increase to the # of apps in your account, this might be worth a shot to correct the issue. Seems like there might be a behind-the-scenes quote limit for apps deployed via the AWS Amplify service, so requesting a limit increase might correct this issue.

It helped for me, I used only 1 app and couldn't create another one in the same region, the quotas were 25, I just increased to 26 and it started working. Only one issue that they don't increase quotas immediately, you need to wait about 1-2days

**Comment by StanislavStadnyk** [comment] 2024-01-31 23:18
> I get the same message and I only have 1 app.

Please check it https://github.com/aws-amplify/amplify-hosting/issues/2797#issuecomment-1920154305

**Comment by StanislavStadnyk** [comment] 2024-05-27 09:12
> Hi, did somebody find any solution of this? I am still getting the exact same error. I can't create amplify app. My default service quota for app in the region and in that aws account is 25, I have only 1 app, and I am still getting error.

Read my comment above, even if you use 1 app and have the limit of 25, request a new limit for example 26, after it should work, I think some issue on their side

**Comment by kuber-** [comment] 2024-06-20 00:09
For anyone else still experiencing similar issue. We had this issue across all our AWS accounts. We had only 1 amplify app and couldn't add another; CLI and console, both had same result. 

The **solution** was what's shared above. We contacted AWS support and the issue was resolved within a day. Besides sharing that the problem was with only one of our accounts, no further details were shared.

**Comment by Jay2113** [comment] 2024-06-24 21:39
Hey everyone, If you're encountering the issue mentioned in this thread, please check my comment at https://github.com/aws-amplify/amplify-backend/issues/1462#issuecomment-2103437190 for the root cause and steps to resolve it. We've also recently improved the error message to provide better clarity. I'll be closing this thread now. Thanks!

**Closed by Jay2113** 2024-06-24 21:39 UTC
Labels: bug, backend-builds
