### ISSUE TITLE
An error occurred during the publish operation

### ISSUE THREAD

**Issue by campbellwarren** [aws-amplify/amplify-hosting#1124] opened 2020-10-09 12:59 UTC
** Please describe which feature you have a question about? **
AWS Amplify Console

** Provide additional details**
I'm trying to follow the tutorial to create a fullstack app with node/react/graphsql (https://docs.amplify.aws/start/getting-started/hosting/q/integration/react).  I get all the way to the very last step, (amplify publish) and I get an error:
√ Zipping artifacts completed.
× Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation

Any advice about where to look next is appreciated.

**Comment by ganipcanot** [comment] 2020-10-09 16:32
Would you be able to share your `appId` (It's part of the app ARN on the General Settings page) and `region`?

**Comment by campbellwarren** [comment] 2020-10-09 18:30
d2i4pheun49pcp
us-east-1

Note: I have been able to workaroud the problem by zipping the contents of the build folder,uploading to S3 and importing. 'drag and drop' failed similarly to "amplify publish".  While the workaround helps, I would love to be able to get it working as it should.

**Comment by dabernathy89** [comment] 2020-10-19 11:35
I had the same issue, and the resolution for me was to use a profile with administrator access in the Amplify CLI. I tried using a profile with this policy at first:

https://docs.amplify.aws/cli/usage/iam

So there must be some missing permission in that policy, but which particular one is absent is not obvious from the error message.

**Comment by litwicki** [comment] 2020-11-11 17:33
@campbellwarren are you still experiencing any issue? Does the proper profile/policy work for you as well?

**Comment by gkpty** [comment] 2020-11-25 21:43
Im having the same issue. runnning amplify publish fails and drag and drop in the amplify console also fails. Just updated to version 4.35 of the cli but still failing..

**Comment by litwicki** [comment] 2020-11-25 21:50
@gkpty are you in us-east-1? We are continuing to investigate increased API error rates in US-EAST-1 region.

**Comment by gkpty** [comment] 2020-11-25 21:50
@litwicki Yes, the app is in us-east-1

**Comment by Usama-Tahir** [comment] 2020-11-26 21:02
I am also facing the same issue. My region is also us-east-1.

**Comment by litwicki** [comment] 2020-11-26 21:05
The issue in US-EAST-1 is now resolved. However builds that were in progress may need to be restarted as a result. If you're not able to cancel/restart any build that was "stuck" please let us know here.

**Comment by campbellwarren** [comment] 2020-11-26 21:58
I never got this to work. I was able to work around it by uploading the
build to S3 and then importing from s3 to amplify.

**Comment by rossbishop** [comment] 2020-11-27 13:28
Having what could be the same problem on eu-west-2. I'm doing manual CI/CD via GitHub actions and get this error in my output:

`Publish started for amplifyhosting
command execution terminated with error
An error occurred during the publish operation
Error: Process completed with exit code 1.`

At first I thought there was an issue with the Amplify CLI action I was using but it seems like there is actually a bug as I've run into the exact same running my own workflow.

I dropped using the front end CI/CD because I was getting freezes when running Cypress, had to recreate my entire app from scratch to go back to manual deployment and now I can't publish my site even when doing everything manually myself.

I'm using access/secret keys for a user that has AdministratorAccess, so it shouldn't be some strange policy based issue either.

Using 4.35.0 locally where it's working, 4.36.0 in my action.

This issue is a complete show stopper for me; I cannot automate my site.

**Comment by litwicki** [comment] 2020-11-27 23:05
@rossbishop really sorry to hear about your difficulties, this is not how things should be working. Can you share your appId here, or if you have anything else you can share with us to verify/reproduce the problem with please send to aws-amplify-customer@amazon.com and we will do whatever we can to get you unblocked.

**Comment by mybNa** [comment] 2020-12-02 06:14
We have the same issue. Since day one "amplify publish" has not worked for us. Also, since we use 3rd party who create roles/policies for us; and is not willing to add IAM policies in the amplify service role. We get exact same error mentioned in the first comment.
We would like to know exactly what policies we need in the role to get this working. And if policy is not the issue what could be the cause for such failure. I wish AWS would give a better stack trace, right now it's such a black box and it's frustrating.

**Comment by rossbishop** [comment] 2020-12-02 17:34
> @rossbishop really sorry to hear about your difficulties, this is not how things should be working. Can you share your appId here, or if you have anything else you can share with us to verify/reproduce the problem with please send to [aws-amplify-customer@amazon.com](mailto:aws-amplify-customer@amazon.com) and we will do whatever we can to get you unblocked.

My actual issue is detailed here - it was a defaults issue with build commands for projects created on Windows that were then being deployed on Linux in the cloud. See https://github.com/aws-amplify/amplify-cli/issues/5990.

Thanks.

**Comment by stefvanderwel** [comment] 2020-12-10 09:04
I fixed this by adding the AdministratorAccess permission to my Amplify IAM user.

**Comment by Alt-Pod** [comment] 2021-01-09 17:10
@stefvanderwel You are a legend, thank you so much.

**Comment by createdbykartik** [comment] 2021-01-15 02:05
I upgrade my amplify and got a more verbose error message, try it and see what exactly is going wrong. 
`npm i -g @aws-amplify/cli`

**Comment by Jay2113** [comment] 2023-06-28 21:53
Hey everyone 👋 , thanks for your continued patience and apologies for the delayed response on the thread.

I performed a quick test and was able to successfully deploy a fullstack Amplify app by following the step by step instructions outlined in this documentation: https://docs.amplify.aws/start/getting-started/installation/q/integration/react/

Amplify CLI version used: 12.1.0

I am going to close this thread but please feel free to open a new GitHub issue if you are experiencing issues with Amplify Hosting. Thank you!

**Closed by Jay2113** 2023-06-28 21:53 UTC
Labels: documentation, usability, manual-deploy, backend-environment
