### ISSUE TITLE
Deployment is not reflecting in the UI

### ISSUE THREAD

**Issue by gouravbhardwaj** [aws-amplify/amplify-hosting#3002] opened 2022-09-22 06:44 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

344380166394

### Region

us-east-1

### Amplify Hosting feature

Build settings

### Describe the bug

When i deploy my latest changes to my master branch, the deployment is successfully completed in Amplify console but i don't see any changes in the UI. There are no failures in the log during the deployment.

Please assist as what can be the root cause of this issue.

### Expected behavior

After successful deployment the latest changes should be rendered in the UI, this is not a cache issue i have confirmed.

### Reproduction steps

1. Commit code changes to the master branch
2. Deployment starts in Amplify and successfully completed
3. Refresh the UI, no changes are rendered

**Comment by smic-ops** [comment] 2022-09-22 08:13
Hello, we also encountered this issue. In our case we are using custom domains. We had a hard time figuring what's causing this issue too. Here's what we have found out so far:

1. The URL (with the custom domain) we are using for the site is loading the wrong version.
2. The amplify site url (https://?.?.amplifyapp.com) is loading the correct version of the site.
3. Deploy logs shows that Amplify created new Cloudfront distribution and S3 deployment bucket in our account
4. In the "Rewrites and Redirects" section, we saw that the newly created Cloudfront distribution was created but the old one is still there.

Deleting the old Cloudfront distribution and setting the right priority for the new Cloudfront distribution created in the deploy stage was the workaround in our case.

We are using Amplify for more almost a year now and this is the first time we encountered this issue.

**Comment by smic-ops** [comment] 2022-09-22 08:23
I think the issue is also resolved in this support ticket.
https://github.com/aws-amplify/amplify-hosting/issues/2982

**Comment by multivoltage** [comment] 2022-09-22 13:51
@smic-ops Did you need to apply your solution (deleting the old cloudfront..) every commit?

**Comment by hloriana** [comment] 2022-09-22 16:40
> @smic-ops Did you need to apply your solution (deleting the old cloudfront..) every commit?

Hi @smic-ops  👋🏽 You only need to perform the steps once. We have root caused and mitigated this issue so future deployments should not run into this behavior.

**Comment by hloriana** [comment] 2022-09-22 16:42
Closing this issue as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2982. Please defer to that issue for any additional updates.

**Closed by hloriana** 2022-09-22 16:42 UTC
