### ISSUE TITLE
Aws amplify deployment - not deleting existing cloudfront and lambda functions.

### ISSUE THREAD

**Issue by Raghunath-SK** [aws-amplify/amplify-hosting#2655] opened 2022-03-18 05:21 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3l13wla9k4s7i

### Region

eu-west-2

### Amplify Hosting feature

Not applicable

### Describe the bug

Whenever a new deployment is happening in the amplify, I notice that amplify is creating CloudFront and lambda resources for this new deployment(which is expected behavior). 

But the old CloudFront (which is created by amplify in the previous deployments) is just marked as disabled , and it is not deleted.  Same way for lambda, old lambda's are not deleted.

Every time after 5- 10  amplify deployments, I'm manually deleting the CloudFront and lambda from the UI-console. 

### Expected behavior

Whenever a new deployment is successful in the amplify, I expect the old CloudFront and lambda functions should be deleted, instead of marking disabled.  It is not deleted even after 5 days, atleast it should get deleted automatically after 2-3 days.

### Reproduction steps

Deploy any sample ssr app in the aws amplify with the domain association. Once the first deployment is completed, change the branch for the app and do the deployment again. After this new branch deployment is successful. You can navigate to CloudFront distribution page and you can notice the old CloudFront distributions are marked as disabled status, but not deleted. It is not deleted even after some days.

Same thing applies to the lambda function. Old lambda's are not deleted.

**Comment by arbass22** [comment] 2022-03-30 00:26
Definitely seeing this as well. Its even more of a problem since there is a low quota for Lambda@Edge distribution so the Amplify builds start to failing with the error: "TooManyDistributionsWithLambdaAssociations: Completing this action would cause the maximum number of distributions with Lambda function associations per owner to be exceeded (maximum allowed is 25)."

So not only does this issue cause out account to be polluted with distributions and lambda functions that will never be used again, but it actually complete breaks Amplify's builds and deployments.

**Comment by arbass22** [comment] 2022-03-30 00:36
Seems like this has been an open issue for a few months #2424 https://github.com/aws-amplify/amplify-hosting/issues/2424

**Comment by Alek-S** [comment] 2022-03-30 02:52
Also related to #2605

**Comment by hloriana** [comment] 2022-03-31 17:54
Hi @Raghunath-SK @arbass22 @Alek-S 👋🏽 thank you for highlighting this issue and providing feedback. I'm working with the service team to prioritize this issue.

**Comment by hloriana** [comment] 2022-03-31 18:21
I will close this issue as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2424. Please enable notifications for that issue so you will be notified when the fix has been rolled out.

**Closed by hloriana** 2022-03-31 18:21 UTC
Labels: bug
