### ISSUE TITLE
Manual Deployment no longer reflecting changes

### ISSUE THREAD

**Issue by dereke55** [aws-amplify/amplify-hosting#2860] opened 2022-07-11 20:32 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1prdls927k8sp

### Region

us-east-2

### Amplify Hosting feature

Manual deploys

### Describe the bug

Upon building React application locally, and then 'drag & drop' the `build` folder from local windows explorer onto the `Choose files` area of the AWS UI, wait for the deployment to complete - status changes to `Deployment successfully completed`, and then refreshing web page (via custom domain), the changes are not reflected.

### Expected behavior

Upon successful deployment, and refresh of web page, the changes should be reflected

### Reproduction steps

1. Generate new React build locally via `yarn build`
2. Drag and Drop the `build` folder from Windows Explorer on to `Choose files` portion of the AWS Web UI
3. Wait for deployment to complete - status changes to `Deployment successfully completed`
4. Refresh web page via custom domain

### Additional information

* There have been over 70 builds that have successfully completed in this manner
* No AWS Amplify settings were changed
* No changes to the custom domain
* Cache has been cleared multiple times, along with browsing via other devices to no avail

**Comment by dereke55** [comment] 2022-07-11 20:41
Upon further testing, it seems the changes ARE reflected on the "App Id" subdomain:

**Comment by greendrake** [comment] 2022-07-12 04:26
I just started using Amplify yesterday and bumped into this exact problem when trying to update the app.
Did it ever work before?
Maybe it only works when deploying from repositories?

**Comment by dereke55** [comment] 2022-07-12 13:26
Thank you @greendrake for referencing #2846 - I missed this.

I have deployed this way for over a year without issue, so I'm not sure what has changed.

re: CloudFront - when originally setting up the Lambda project and deployment, there was some "automagic" related to CloudFront.  I'm not following re: "I note that the CloudFront distribution serving the app does not belong to the AWS account".

It does feel like something has changed or there is a sync / cache issue.

**Comment by dereke55** [comment] 2022-07-12 14:50
Ah yes.  I completely agree.

**Comment by dereke55** [comment] 2022-07-19 15:29
> > Any update on this (or related) issue?
> 
> I have ditched Amplify for S3+CloudFront, and happy with it.

Good to know.  Thank you!

**Comment by dereke55** [comment] 2022-07-19 15:32
I was able to force the update / sync by following the steps from @soplan in #2844:

* Go to your app
* under App Settings select Domain Management
* Manage Sub Domains
* Click Disable
* Update
* Wait... and Click Enable again

**Comment by oliver-leung** [comment] 2022-07-20 22:42
We've root-caused the issue and are currently working on the fix. In the meantime, please use one of the following workarounds:
1. Disable, then re-enable the custom domain in App Settings > Domain Management > Manage subdomains
1. Only upload compressed .zip build artifact folders

**Comment by hloriana** [comment] 2022-10-06 21:04
Closing as duplicate of #2846.

**Closed by hloriana** 2022-10-06 21:04 UTC
Labels: bug
