### ISSUE TITLE
node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)

### ISSUE THREAD

**Issue by xkeshav** [aws-amplify/amplify-hosting#3750] opened 2023-10-08 16:48 UTC
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1c6hzkoiamnhy

### Region

us-east-1

### Step

Build fail

### Status

Failed

### Issue or question

update Astro which require node js version 18.1.4.1 and I have updated the node js version by changing build setting but build not getting completed as it gives error

Amazon  AWS amplify use build image Amazon Linux 2  

build log: https://us-east-1.console.aws.amazon.com/amplify/home?region=us-east-1#/d1c6hzkoiamnhy/update/4?step=BUILD

### Error message

# Starting phase: preBuild
2023-10-07T18:15:08.707Z [INFO]: # Executing command: npm ci
2023-10-07T18:15:08.708Z [WARNING]: node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by node)
                                    node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by node)
2023-10-07T18:15:08.709Z [ERROR]: !!! Build failed
2023-10-07T18:15:08.709Z [ERROR]: !!! Non-Zero Exit Code detected
2023-10-07T18:15:08.709Z [INFO]: # Starting environment caching...
2023-10-07T18:15:08.709Z [INFO]: # Environment caching completed
Terminating logging.

### Additional information

Using Astro v3 for build and this is working fine till previous version of astro.. here is my package.json 

```json
{
  "name": "grateful-galaxy",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/mdx": "^0.17.2",
    "@astrojs/rss": "^2.1.1",
    "@astrojs/sitemap": "^1.1.0",
    "astro": "^3.2.0"
  },
  "devDependencies": {
    "typescript": "^5.2.2"
  }
}
```

**Comment by Jay2113** [comment] 2023-10-09 20:17
Closing as it's a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/3754.

**Closed by Jay2113** 2023-10-09 20:17 UTC
Labels: question, duplicate
