### ISSUE TITLE
AWS amplify build failed

### ISSUE THREAD

**Issue by PierreBalazuc** [aws-amplify/amplify-hosting#2009] opened 2021-06-29 15:07 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2y4s18nsmd981

### Region

eu-central-1

### Amplify Console feature

Custom builds

### Describe the bug

Hello,

The bug come when i deploy my modification on git and then build by amplify. The build failed everytime at :
**Starting SSR Build...**

and i go this message : 

> Starting SSR Build...
> 2021-06-29T14:01:29.603Z [ERROR]: Error: 'Command failed with exit code 1: node_modules/.bin/next build',
>                                   command: 'node_modules/.bin/next build',
>                                   exitCode: 1,
>                                   signal: undefined,
>                                   signalDescription: undefined,
>                                   stdout: 'Loaded env from /codebuild/output/src615757906/src/***/.env\n' +
>                                   'warn  - No build cache found. Please configure build caching for faster rebuilds. Read more: https://err.sh/next.js/no-cache\n' +
>                                   'info  - Creating an optimized production build...\n' +
>                                   'Attention: Next.js now collects completely anonymous telemetry regarding usage.\n' +
>                                   "This information is used to shape Next.js' roadmap and prioritize features.\n" +
>                                   "You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:\n" +
>                                   'https://nextjs.org/telemetry\n',
>                                   stderr: 'Browserslist: caniuse-lite is outdated. Please run:\n' +
>                                   'npx browserslist@latest --update-db\n' +
>                                   'Failed to compile.\n' +
>                                   '\n' +
>                                   "ModuleNotFoundError: Module not found: Error: Can't resolve 'net' in '/codebuild/output/src615757906/src/***/node_modules/tunnel-agent'\n" +
>                                   '\n' +
>                                   '\n' +
>                                   '> Build error occurred\n' +
>                                   'Error: > Build failed because of webpack errors\n' +
>                                   '    at build (/codebuild/output/src615757906/src/***/node_modules/next/dist/build/index.js:15:918)\n' +
>                                   '    at runMicrotasks (<anonymous>)\n' +
>                                   '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
>                                   failed: true,
>                                   timedOut: false,
>                                   isCanceled: false,
> Terminating logging...
> 
> 
4 days earlier i did a realease and everything work perfectly my app build with no error.
but today i can't get rid of this error. i search everything on the net but nothing work to resolve it.

I don't understant why next.js come here because i never used it in my project ( react app), and i don't understant why the build start to do "SSR Build". The last build (the worked one) , i look at the log and the command SSR BUILD is not used.

Everything were fine 4 days ago...
Does your guys have a solution for this ?

### Expected behavior

Build success with no error like the 25 past succed build.

### Reproduction steps

1. deployed my code in Git
2. automatic deployement with aws amplify

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - nvm use $VERSION_NODE_12
        - npm ci
    build:
      commands:
        - nvm use $VERSION_NODE_12
        - node -v
        - npm run-script build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

The last modification i did on my code where : 
- call a /Get with API gateway
- install xml2js with npm
- install node-fetch with npm

that all my changes

**Comment by PierreBalazuc** [comment] 2021-06-29 20:12
Now i have this kind of error : 

> ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/codebuild/output/src914097980/src/secureasy/node_modules/request/lib'\n" +

Always at "moduleNotFoundError"

**Comment by PierreBalazuc** [comment] 2021-06-29 21:41
Even if i backup and deploy the lastest succesful commit, i still got the error.

> ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/codebuild/output/src914097980/src/***/node_modules/request/lib'\n" +

**Comment by Athena96** [comment] 2021-07-27 17:28
Hi all, we've recently made improvements to our SSR error logging and have added support for Next.js 10/11. 
Please follow this guide to upgrade to our latest support of Next.js: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#update-app-nextjs-version

**Comment by RealDrewKlayman** [comment] 2021-07-28 00:07
This is directly related to:
https://github.com/aws-amplify/amplify-console/issues/2098

**Comment by Jay2113** [comment] 2024-03-07 04:40
This issue is a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2098 and it seems isolated to Next v11. We have since launched improved support for Next.js versions 12 and 13 so this should no longer be an issue.

**Closed by Jay2113** 2024-03-07 04:40 UTC
Labels: ssr
