### ISSUE TITLE
Cannot Delete Amplify App `ResourceNotFoundException`

### ISSUE THREAD

**Issue by Sma-Das** [aws-amplify/amplify-hosting#2868] opened 2022-07-14 13:12 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1uv2d54o6zooq

### Region

ap-south-1

### Amplify Hosting feature

Not applicable

### Describe the bug

I cannot remove the app. I have tried to reinitialize it using various methods I found on StackOverFlow and GitHub, however, I cannot even access the overview section of the app as it stalls out

### Expected behavior

Delete the app

### Reproduction steps

1. I pushed some new changes to my Amplify app through the CLI
2. The deletion of a lambda function was not completing and kept cycling
3. I saw a post on StackOverFlow to remove the stack
4. I accidently removed the root stack
5. I tried to delete the app and migrate it to a new app using the changes I had locally
6. I cannot delete the old app

**Comment by hloriana** [comment] 2022-07-14 15:43
Hi @Sma-Das 👋🏽 to delete the application run `aws amplify delete-backend-environment --app-id <value> --environment-name <value>` https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html

**Comment by hloriana** [comment] 2022-07-27 21:49
Hi @Sma-Das If the the CloudFormation stack associated with the backend environment no longer exists then yes, you will need to manually delete those resources. 

Closing this as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2548

**Closed by hloriana** 2022-07-27 21:49 UTC
Labels: bug, question, console

**Comment by johnpc** [comment] 2022-09-27 01:08
When deleting via Amplify console, the error reported

```
ResourceNotFoundException 
```

has been fixed. you should be able to re-try deleting your app from Amplify console.
