### ISSUE TITLE
Jekyll build broken

### ISSUE THREAD

**Issue by tuananhle7** [aws-amplify/amplify-hosting#3445] opened 2023-04-26 01:56 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d4d1r1668d2gf

### AWS Region

us-east-1

### Amplify Hosting feature

Frontend builds

### Question

My recent Jekyll build on AWS Amplify mysteriously fails with
```
sass-embedded-1.62.1-x86_64-linux-musl requires rubygems version >= 3.3.22,
                                    which is incompatible with the current version, 3.1.6
```

This didn't happen before and I don't know how to get this build to work.

This is the full build log: https://gist.github.com/tuananhle7/e00d20b4062e10bc2573280f053356ce

For reference, here is a build log for the last successful build: https://gist.github.com/tuananhle7/bef7bbd28b90c156689fc46a07d28b00

Please help.

**Comment by 2BAB** [comment] 2023-05-05 11:53
Same issue for me. Upgraded to the latest 2.5.0 did not work either. https://github.com/2BAB/2BAB-Engineering-Blog/actions/runs/4893043497/jobs/8735524183

**Comment by nadetastic** [comment] 2023-05-10 18:38
Closing this as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/3473

**Closed by nadetastic** 2023-05-10 18:38 UTC
Labels: question
