### ISSUE TITLE
Redirect to www url along with query string params

### ISSUE THREAD

**Issue by ParulSharma2622** [aws-amplify/amplify-hosting#2972] opened 2022-09-07 09:53 UTC
If there's a way out to preserve query string parameters when a non www url redirects to www url. Please consider the following use case to understand it better.

We have an amplify react application and we are passing some random codes in query string parameters and those random codes will help us to identify some important information regarding the customer at some later stage. But query string parameters are removed when a customer comes from a non www url. 

for example : https://abc.com/some-keyword/?param1=test&param2=test2 >> It must redirect to https://www.abc.com/some-keyword/?param1=test&param2=test2

Please let us know how this can be done using amplify rewrite and redirect headers.

Here is the app details :
App Id : d280tc8bca7hos
App region : ap-southeast-2

Thanks,

**Comment by hloriana** [comment] 2022-09-26 19:18
Hi @ParulSharma2622 thank you for raising this question. We are investigating this internally to determine if there is a workaround for this behavior. We will update this issue shortly.

**Comment by hloriana** [comment] 2022-10-11 21:30
Hello @ParulSharma2622 👋🏽 According to the Amplify documentation, dropping the query params is intended behavior:

> If the destination address for the matching rule has query parameters, query parameters aren't forwarded. For example, if the destination address for the redirect is https://example-target.com?q=someParam, query parameters aren't passed through.


Please read more about implementing query params here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#query-parameters

We are tracking this as a feature request. Closing as a duplicate of #97

**Closed** 2022-10-11 21:30 UTC
Labels: question, redirects
