### ISSUE TITLE
Amplify builds fail without logs

### ISSUE THREAD

**Issue by yassinecc** [aws-amplify/amplify-hosting#3410] opened 2023-04-06 11:46 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d2kumq5x0abp49 / dfzff0h6ditve

### AWS Region

eu-west-3

### Amplify Hosting feature

Frontend builds

### Describe the bug

The builds immediately fail after 0 seconds for multiple apps with a generic message and no logs
![image](https://user-images.githubusercontent.com/31844581/230367087-a7865a91-6bf5-430d-ba06-4d15118c2eae.png)

The code / build settings did not change since the last successful build

### Expected behavior

Build should not randomly fail, and should give error logs in this case

### Reproduction steps

Redeploy any previously deployed version

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jbreemhaar** [comment] 2023-04-06 11:47
Yes, same here. 4 different amplify hosting apps, all failing without build logs.

**Comment by gomesLuis479SV** [comment] 2023-04-06 11:50
same here!

**Comment by ansbr** [comment] 2023-04-06 11:51
Same here

**Comment by jbrawnjr** [comment] 2023-04-06 11:51
I am also experiencing this issue. Even redeploying a previous version that built successfully from just a few days ago will fail in the same way as new builds.

**Comment by godasisatish** [comment] 2023-04-06 11:54
Same here

**Comment by ArianHamdi** [comment] 2023-04-06 11:58
Same here

**Comment by vafPER** [comment] 2023-04-06 11:58
Same here

**Comment by metuuu** [comment] 2023-04-06 12:03
Same here

**Comment by rahul799** [comment] 2023-04-06 12:04
Same here

**Comment by omkar-pai** [comment] 2023-04-06 12:06
Facing same issue please fix. Unable to deploy anything.

**Comment by rnunes-i9** [comment] 2023-04-06 12:06
Same here, even with previous successful builds

**Comment by sukoxtuto** [comment] 2023-04-06 12:06
Affecting us as well. Redeploying old builds does not work either.

**Comment by burgi** [comment] 2023-04-06 12:07
Facing the same issue with a static very simple web site

**Comment by piotrmoszkowicz** [comment] 2023-04-06 12:09
For us exactly the same. Exact same code was built yesterday, but currently with moving to another account it fails.

**Comment by srweeks** [comment] 2023-04-06 12:11
Same on eu-west-1

**Comment by adamparslow** [comment] 2023-04-06 12:15
Same on `ap-southeast-2`

**Comment by phyzixmusic** [comment] 2023-04-06 12:17
Spoke to aws support, told me there is a global outage with no ETA

**Comment by shrikanthkr** [comment] 2023-04-06 12:23
Same here!

**Comment by azmathmoosa** [comment] 2023-04-06 12:23
same on ap-south-1.  Is there any workaround or quick fix!  we have a client demo tomorrow and now we are stuck.

**Comment by DMuirheadAcetech** [comment] 2023-04-06 12:31
Happening here in EU-Central-1

**Comment by jbreemhaar** [comment] 2023-04-06 12:36
> same on ap-south-1. Is there any workaround or quick fix! we have a client demo tomorrow and now we are stuck.

If you only need the hosting stuff, try Vercel.

**Comment by tscole** [comment] 2023-04-06 12:54
Same in eu-west-2

**Comment by arundna** [comment] 2023-04-06 12:59
Hi All, We have identified the root cause of an issue that is causing increased latencies when starting new builds. We will provide an update once we have more information.

**Comment by Milan-Shah** [comment] 2023-04-06 15:11
Between 03:45 AM PST and 06:31 AM PST, we experienced increased latencies when starting new builds. The issue has been resolved and the service is operating normally. 🎉 

If you see any further issues, please let us know. We are here to help!

**Closed** 2023-04-06 15:28 UTC
Labels: bug, pending-triage

**Comment by hloriii** [comment] 2023-04-06 15:29
We apologize fore the inconvenience here. Please open a new issue if you experience unintended behaviors. This issue has been closed as resolved. Thank you!

**Comment by yassinecc** [comment] 2023-04-06 15:43
@Milan-Shah builds seem OK now, although they take twice as long as usual
