### ISSUE TITLE
token expiring after 1 hour, build failing for long build

### ISSUE THREAD

**Issue by gauravsapkal** [aws-amplify/amplify-hosting#3458] opened 2023-05-04 07:36 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting questions](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

static page generation

### AWS Region

ap-south-1

### Amplify Hosting feature

Build settings, SSR

### Question

We are facing an issue while implementing ISR in our NextJS application deployed on AWS Amplify.
Currently, we are generating more than 22,000 static pages, which has increased our NextJS application build time to more than an hour. However, we are encountering an error message during the build process which states that the AWS token generated at build time has expired after one hour. The error message reads as follows: "ExpiredToken: The provided token has expired. at Request.extractError (/root/.//node_modules/@sls-next/s3-static-assets/node_modules/aws-sdk/lib/services/s3.js:711:35)".
We are looking for a solution to either increase the time for the token or refresh the token to avoid the build failure. Alternatively, if there is any other way to implement this process, we would appreciate your guidance.
I would appreciate it if you could please assist us in resolving this issue as soon as possible.

Thank you in advance for your assistance.

**Comment by hloriii** [comment] 2023-05-04 13:08
Hi @gauravsapkal 👋🏽 could you please provide your appID so we can look further into this error?

**Comment by hloriii** [comment] 2023-05-04 13:37
This timeout is a hard limit that we cannot increase at this time. Unfortunately we do not have any workarounds for this limitation. It would be best to try to reduce the amount of pages that are statically generated. We understand this limitation is an inconvenience under these circumstances and we are tracking this internally to find a path forward.

Closing this as a duplicate of #2751. Please continue to follow that issue for any updates regarding this behavior.

**Closed by hloriii** 2023-05-04 13:37 UTC
Labels: investigating, frontend-builds, usability, response-requested
