### ISSUE TITLE
Next.js - Failed to update prerender cache 

### ISSUE THREAD

**Issue by grundmanise** [aws-amplify/amplify-hosting#3719] opened 2023-09-21 14:59 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-hosting/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### App Id

d15u55p1unr8ob

### AWS Region

eu-central-1

### Amplify Hosting feature

SSR

### Frontend framework

Next.js

### Next.js version

13.4.13

### Next.js router

App Router

### Describe the bug

Next.js dynamic page caching does not seem to work with Amplify. I can observe prerender cache related errors in the CloudWatch Amplify group logs:

```
Failed to update prerender cache for /setup/carrier-setup/f576bb60-e349-455d-9acb-e7d025ce8dcc
[Error: EROFS: read-only file system, open '/tmp/app/.next/server/app/setup/carrier-setup/f576bb60-e349-455d-9acb-e7d025ce8dcc.html']
{
 errno: -30,
 code: 'EROFS',
 syscall: 'open',
 path: '/tmp/app/.next/server/app/setup/carrier-setup/f576bb60-e349-455d-9acb-e7d025ce8dcc.html'
}
```

### Expected behavior

Prerender cache is updated successfully for Next app deployed to Amplify.

### Reproduction steps

1. Create a dynamic route segments page which uses `async generateStaticParams`
2. Deploy production build to Amplify hosting on Web compute platform
3. Observe CloudWatch logs

### Build Settings

```yaml
frontend:
  phases:
    preBuild:
      commands:
        - nvm use 18
        - yarn install --frozen-lockfile --production=false
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Log output

<details>

```
Failed to update prerender cache for /setup/carrier-setup/f576bb60-e349-455d-9acb-e7d025ce8dcc
[Error: EROFS: read-only file system, open '/tmp/app/.next/server/app/setup/carrier-setup/f576bb60-e349-455d-9acb-e7d025ce8dcc.html']
{
 errno: -30,
 code: 'EROFS',
 syscall: 'open',
 path: '/tmp/app/.next/server/app/setup/carrier-setup/f576bb60-e349-455d-9acb-e7d025ce8dcc.html'
}
```

</details>

### Additional information

In the build output I can observe the page is generated as SSG
```
└ ● /setup/carrier-setup/[templateId]      923 B           209 kB

●  (SSG)     automatically generated as static HTML + JSON 
```

**Comment by Jay2113** [comment] 2023-09-25 17:00
Hi @grundmanise 👋 , thanks for raising this! As stated by @owenfarrell, this looks like a duplicate of the issue outlined here: https://github.com/aws-amplify/amplify-hosting/issues/3707. 

I am going to close this thread and I'll recommend monitoring the other thread for updates on this issue.

**Closed by Jay2113** 2023-09-25 17:00 UTC
Labels: compute, duplicate
