### ISSUE TITLE
Deploy failed to complete successfully. But logs says Deployment Successful

### ISSUE THREAD

**Issue by abhay330** [aws-amplify/amplify-hosting#3007] opened 2022-09-27 12:40 UTC
**Describe the bug**
Amplify Deploy Stage is marked failed in the CI however the log show deployment successful

![image](https://user-images.githubusercontent.com/22653892/192527923-d97c2cb8-5fbc-4fad-be19-523f73a038ed.png)

![image](https://user-images.githubusercontent.com/22653892/192528258-d57063d2-c801-485a-9240-7d1b0491dad4.png)

**To Reproduce**

1. Click on Redeploy this version for the branch
2. Provision and Build stages pass successfully, fails at Deploy Stage and verify is never invoked

**Expected behavior**
Successfully completion of all the stages - Provision, Build, Deploy & Verify

**Comment by hloriana** [comment] 2022-09-27 15:17
Hi @abhay330 👋🏽 thank you for raising this issue. We have added the task of improving our error logs to our backlog so that the error is clear to the user. In the mean time, we will need your App ID so that we can investigate why the deployment is failing for your application.

**Comment by abhay330** [comment] 2022-09-28 04:20
Hello @hloriana 

This is my App ID : d1i25mdk2vclxx
ARN: arn:aws:amplify:us-east-1:xxxxxxxxxx:apps/d1i25mdk2vclxx

**Comment by hloriana** [comment] 2022-09-30 21:22
Hi @abhay330 thanks for providing these details. We are working on mitigating this issue for you. We will update this issue shortly.

**Comment by hloriana** [comment] 2022-09-30 22:34
The team has resolved this issue for your application. You can redeploy your app and you should no longer see this behavior. Closing this issue as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2976. Please comment on that issue if you continue to experience this behavior. Thank you!

**Closed by hloriana** 2022-09-30 22:34 UTC
Labels: deploy
