### ISSUE TITLE
Unable to delete the Amplify app that is created by one of our peers

### ISSUE THREAD

**Issue by SaiTejaMakani** [aws-amplify/amplify-hosting#2454] opened 2021-12-14 23:15 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Region

us-west-2

### Describe the bug

I am trying t clean up the unwanted amplify apps present in our account. From the Ui or from the CLI I am unable to delete the app: dtzum9ganubuq  account id: 058815775742. App name as we see in the amplify console: rnirnber_hello_world

### Expected behavior

I am expecting this app to be completely removed any resources used by it should be deleted from our account.

### Reproduction steps

C:\Users\Makanist>amplify pull --appId dtzum9ganubuq --envName staging
? Select the authentication method you want to use: AWS profile

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

? Please choose the profile you want to use the default
Amplify AppID found: dtzum9ganubuq. Amplify App name is: rnirnber_hello_world
Backend environment staging found in Amplify Console app: rnirnber_hello_world
Error downloading #current-cloud-backend.zip from deployment bucket: amplify-rnirnberhelloworld-staging-181944-deployment, the error is: The specified bucket does not exist

### Build Settings

```yaml
Nothing.. its pure empty hello world app.
```

**Comment by hloriana** [comment] 2021-12-15 18:20
Hi @SaiTejaMakani 👋🏽 thanks for raising this! Try running this command to completely remove your backend: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`.

You should then be able to delete the frontend from the console. 

What happened when you tried to delete the app from the console?

**Comment by SaiTejaMakani** [comment] 2021-12-15 18:35
No use

C:\Users\Makanist>amplify delete --app-id dtzum9ganubuq  --environment-name staging
? Are you sure you want to continue? This CANNOT be undone. (This will delete all the environments of the project from the cloud and wipe out all the local files created by Amplify CLI) Yes
× Project delete failed.

      No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.


When I tried to delete from AWS console page it is saying 
"Invoking remove all backends execution failed"

**Comment by hloriana** [comment] 2021-12-15 18:58
@SaiTejaMakani make sure you add `aws` to the front of the command as this command is from the AWS CLI. Refer to: https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html

**Comment by SaiTejaMakani** [comment] 2021-12-15 19:03
Apologies my bad.. its working. I am able to delete the backend and them able to delete the entire app from the amplify console.

**Comment by hloriana** [comment] 2021-12-15 19:18
@SaiTejaMakani Awesome! The team is aware of this bug in regards to deleting applications and are working to fix it.

**Comment by hloriana** [comment] 2022-07-27 16:34
Closing this as a duplicate of https://github.com/aws-amplify/amplify-hosting/issues/2548. Please follow that issue for updates on the bug fix. Thank you!

**Closed by hloriana** 2022-07-27 16:34 UTC
Labels: bug, console

**Comment by johnpc** [comment] 2022-09-27 01:01
When deleting via Amplify console, the error reported

```
Error downloading #current-cloud-backend.zip from deployment bucket: amplify-rnirnberhelloworld-staging-181944-deployment, the error is: The specified bucket does not exist
```

has been fixed. you should be able to re-try deleting your app from Amplify console.
