### ISSUE TITLE
is there a way I can host an app in 2 different platforms

### ISSUE THREAD

**Issue by kvramyasri7** [aws-amplify/amplify-hosting#3910] opened 2024-02-08 09:25 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Not Applicable

### Is your feature request related to a problem? Please describe:

I have a monorepo with two applications: one in React and another in Next.js. Each project has its own amplify.yml in its root folder. While I was able to build both applications in my Amplify, the CI/CD doesn't work properly because the app's platform should be 'Web' for React and 'Web compute' for Next.js. As a result, I need to manually change it every time I want to deploy one of them.

Also, a follow up question - is it possible to set the AMPLIFY_MONOREPO_APP_ROOT from one of the configuration files?

### Describe how you'd like this feature to work

Generally, my goal is to connect both monorepo folders (react and nextjs) into 1 URL, i.e. https://example.com which is hosted on Amplify. Then, for every example.com/app2, this should show the Next.js app; otherwise, it should show the React app. I was able to achieve this with a rewrite, however, I wonder if there is a simpler way to do it that will also support CI/CD.

**Comment by kvramyasri7** [comment] 2024-02-10 17:02
Any update on this one @Milan-Shah  @ArseniyKotov ?

**Comment by kvramyasri7** [comment] 2024-02-12 04:23
Any update on this one @Milan-Shah @ArseniyKotov ?

**Comment by Milan-Shah** [comment] 2024-02-12 18:42
No updates. We will work closely with our product owner and assign priority to this feature request.

**Comment by kvramyasri7** [comment] 2024-02-12 18:44
Great !!!

**Comment by kvramyasri7** [comment] 2024-02-12 18:46
Hopefully this comes out in next 2-4 years and version in Amplify ❤️. Can not wait to you this in sibling products @Milan-Shah @mauerbac @ArseniyKotov . I am also interested in discussing this with you guys in this coming month as I am planning to visit New York. Seems like a fun feature request

**Comment by kvramyasri7** [comment] 2024-02-12 18:47
Thanks @mauerbac  and @Jay2113  ❤️. You guys are really AWEsoummmm.... (Awesome!!!!)

**Comment by mauerbac** [comment] 2024-02-12 18:51
Duplicate of https://github.com/aws-amplify/amplify-hosting/issues/3907

**Closed by mauerbac** 2024-02-12 18:51 UTC
Labels: feature-request

**Comment by kvramyasri7** [comment] 2024-02-12 18:52
Ummm. I apologize for duplicating issues u guys thought this is **sumyathing** else
