### ISSUE TITLE
Pass url params in rewrites and redirects

### ISSUE THREAD

**Issue by patleeman** [aws-amplify/amplify-hosting#97] opened 2019-09-03 19:48 UTC
** Please describe which feature you have a question about? **
Rewrites and redirects

** Provide additional details**
Hello, I'm trying to set up a 301/302 redirect from a path in my amplify application. i.e. `/test` to another domain i.e. `https://example.com/test`. The redirect works as expected, but if I try to add some url parameters, `/test?utm_test=test` the redirect strips the url parameter and redirects to `https://example.com/test`. With the 200 rewrite, url params don't get stripped.

I want
`/test?utm_test=test&utm_something=something -302-> https://example.com/test?utm_test=test&utm_something=something`

I get
`/test?utm_test=test&utm_something=something -302-> https://example.com/test`

Is there a way to pass along *all* the url parameters in one shot?

As a side note, I am trying to redirect the path including the trailing slash and excluding the trailing slash. i.e. `/test` and `test/`. I know you can use the regex route to do both i.e. `</(\/test)(\/)?/> -> https://example.com/test` but there doesn't seem to be a way to use path parameters with regex paths? 

i.e. `</(\/test\/<path_param>)(\/)?/> --> https://example.com/<path_param>`  or even a way to specify the regex match group? `--> https://example.com/<regex[1]>` or something like that.

Thanks for the help

**Comment by hzhenmin** [comment] 2019-09-05 20:26
1 Currently we do not support redirect with query string, we have added the feature into our backlog
2 <*> can be used to redirect everything after path to another url
example: 
Source: /test/<*> Target: https://example.com/<*> Type: 301/302

**Comment by patleeman** [comment] 2019-09-05 20:51
@hzhenmin Thanks for the `<>` tip. I didn't know you could do that. 👍 

We found a workaround for the querystring issue for now. Thank you.

**Comment by swaminator** [comment] 2019-09-06 01:07
@patleeman could you share your workaround for other users who end up here?

**Comment by patleeman** [comment] 2019-09-06 19:06
@swaminator sure thing.

I ended up doing a 200 rewrite to an endpoint I wrote that returned a 302 redirect to the domain I wanted with the url parameters appended.

Not the best solution but it works for now.

**Comment by JonVisc** [comment] 2020-02-20 18:32
@hzhenmin , Re-asking the question that @patleeman asked.

If we use regex to get a capture group, can we reuse that group?
`</^([^\.]+(?<!\/))$/>` will match for:
`/test`

But not match for:
`/test/`
`/test.html`

So if a user hits `https://example.com/test` is there anyway to say we want to redirect them to `https://example.com/test/` using that capture group?

You mentioned the functionality of a query string in the backlog but I thought more generically it would imply anything in a capture group.  Is there an update if that functionality will be out soon/is out but the documentation is lacking so we don't know the syntax?

**Comment by berniedurfee** [comment] 2020-03-31 02:34
This seems to be breaking OIDC callbacks, where the user is redirected from the IdP back to the app route like: `https://myapp.com/implicit/callback?code=abcxyz`

The user is then immediately redirected by Cloudfront to `https://myapp.com/implicit/callback/` without the query parameters, which breaks the OIDC flow.

The only solution was to force a 200 back to `index.html` using the rewrite rule specified here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa

Though, it's not clear how that's working, without seeing the underlying Cloudfront configuration. It simply stops executing the 301, which preserves the query parameters.

@hzhenmin what's the solution proposed to allow redirects while preserving query parameters in Amplify?

**Comment by poolieweb** [comment] 2020-04-03 16:48
+1 , We are trying to do RegEx with capture groups. Very difficult to replicate redirects from existing systems.

**Comment by awilkins** [comment] 2020-04-07 15:10
Is this feature implemented with a Lambda@Edge? Maybe if we could get access to the source it would become clearer to people?

**Comment by SudduK** [comment] 2020-06-14 05:33
> This seems to be breaking OIDC callbacks, where the user is redirected from the IdP back to the app route like: `https://myapp.com/implicit/callback?code=abcxyz`
> 
> The user is then immediately redirected by Cloudfront to `https://myapp.com/implicit/callback/` without the query parameters, which breaks the OIDC flow.
> 
> The only solution was to force a 200 back to `index.html` using the rewrite rule specified here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa
> 
> Though, it's not clear how that's working, without seeing the underlying Cloudfront configuration. It simply stops executing the 301, which preserves the query parameters.
> 
> @hzhenmin what's the solution proposed to allow redirects while preserving query parameters in Amplify?

Hi berniedurfee,

  Did you resolve the issue with OIDC callback url not preserving parameters?
   
  I am trying to implement OKTA authentication (OIDC) for a React based SPA and trying to host the application into AWS Amplify (I tried initially to host SPA in S3 as static website along with Cloudfront  and had PKCE errors not supporting http protocol with S3 website endpoint and eventually ended trying to use AWS Amplify)

  When deployed to AWS Amplify, application tries to authenticate initially, but redirecting back to callback url (https://domainname.com/implicit/callback) seems to be not routing to the react callback component.
  I tried using a hack to rewrite the callback url, **https://domainname.com/implicit/callback** to **https://domainname.com/#!implicit/callback** in order to route to the **Logincallback** component, but missing code and state parameters which are required to complete authentication.

 Secondly, I was not able to use the regular expression  **(</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>)** redirect for SPA successfully as given in AWS amplify documentation. This redirect rule is working only until redirecting the callback url to index.html and does nothing after that.

 Any thoughts on how to approach this issue?
 Thank you!

Regards,
Sudharshan.

**Comment by bighoot** [comment] 2020-07-22 17:07
> This seems to be breaking OIDC callbacks, where the user is redirected from the IdP back to the app route like: `https://myapp.com/implicit/callback?code=abcxyz`
> 
> The user is then immediately redirected by Cloudfront to `https://myapp.com/implicit/callback/` without the query parameters, which breaks the OIDC flow.
> 
> The only solution was to force a 200 back to `index.html` using the rewrite rule specified here: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa
> 
> Though, it's not clear how that's working, without seeing the underlying Cloudfront configuration. It simply stops executing the 301, which preserves the query parameters.
> 
> @hzhenmin what's the solution proposed to allow redirects while preserving query parameters in Amplify?

Were you ever able to resolve this or build a workaround that allowed for query parameters?

**Comment by FelixRe0** [comment] 2020-07-22 17:42
+1 Same question here. Using </index\.html/> => /404.html [404 Rewrite] #823

**Comment by cmaycumber** [comment] 2020-07-22 18:05
I'm running into the exact same issue using the same setup as @FelixRe0 for a Gatsby site.

**Comment by bighoot** [comment] 2020-07-22 21:12
I guess I can say it feels better to not be the only one struggling with this.

**Comment by bighoot** [comment] 2020-07-22 21:42
Others at my company have recommended trying to build some sort of component that would be able to redirect to where the traffic needs to go (in my case its the callback after logging in to Okta) and somehow preserve the query parameters.  But, unless I misunderstand something, there's literally no way to access those parameters in the app, or any app running in Amplify, because as soon as the call hits that boundary, the query parameters are lost.  Is that everyone else's understanding as well?  Or am I oversimplifying this?

**Comment by cmaycumber** [comment] 2020-07-23 00:04
@bighoot We ended up reaching out to AWS technical support so hopefully they can help; I think that passing query params is a pretty vital task. 

That's how it should work. The redirects are handled on the CloudFront edge server rather than the client.

**Comment by cmaycumber** [comment] 2020-07-23 16:26
We reached out to AWS support and they said that this is currently not supported; referencing this issue. 

@bighoot @FelixRe0 One way that we are currently getting around it is passing the UTM's with the trailing slash on the end of the URL with UTMS like https://www.example.com/products/kit/?example=true. AWS console doesn't remove the query params when the trailing slash is included. Not sure if this supports your use case but it seems like it's working for us for the time being.

**Comment by bighoot** [comment] 2020-07-23 20:50
I added the trailing / to the end of the redirect URL and to the callback route in the angular app and, like magic, the redirect that took away the params vanished.  Thanks!  This seems like a complete hack and I have no idea why it works, but it does.  Thank you again.

**Comment by jlcampos-iies** [comment] 2020-09-01 14:19
Same problem here... stopping an ec2 and starting amplify... everything ok except some issues... one of them refer to authentication from usr/pwd provider during user registration with specific token and tokenId sent by email to the user.... then the user confirm from email through url similar to https://example.com/confirmRegistry?token=value1&tokenId=value2

Adding trailing slash seems not to solve it.

Any new idea???

Thanks in advance

**Comment by gwryssekk** [comment] 2020-09-04 21:13
Hi @jlcampos-iies -- Can you give more detail on your use case?  What is the expected result when the user tries to confirm via https://example.com/confirmRegistry?token=value1&tokenId=value2 and what is the actual result?

**Comment by jlcampos-iies** [comment] 2020-09-05 06:31
Hi @gwryssekk , parameters are used into component to run the provider function that confirms the registry...

`params = new URLSearchParams(window.location.search);`
`token = this.params.get('token');`
`tokenId = this.params.get('tokenId');`

`ngOnInit(){`
`confirmUser(this.token, this.tokenId)`
`.then( () => {`
`... `
`})`
`.catch( err => console.log(err));`
`}`

The confirmUser function its an http POST request and params are always null because of Amplify redirects to https://example.com/confirmRegistry removing them. So user never can be confirmed.

Regards,
Jose Luis Campos

**Comment by FelixRe0** [comment] 2020-09-07 06:02
> Hi @jlcampos-iies -- Can you give more detail on your use case? What is the expected result when the user tries to confirm via https://example.com/confirmRegistry?token=value1&tokenId=value2 and what is the actual result?

Use `https://example.com/confirmRegistry/?token=value1&tokenId=value2` and it will work. Notice the / before the query parameters. 
Still, the amplify team should make any url work...

**Comment by jlcampos-iies** [comment] 2020-09-09 14:46
Hi everyone!

Adding from backend / before the query parameters had desired effect.

Thanks again!

Regards,
Jose Luis Campos

**Comment by grahamd711** [comment] 2020-09-17 04:42
@hzhenmin has there been any progress in adding support for this feature? This is a critical need for simply redirecting from a naked domain https://example.com to the WWW version --> https://www.example.com 

We are not able to preserve any UTM parameters that are crucial to our Jekyll site. Please let me know if there is any type of transparency into the backlog. 

Thank you!

**Comment by carlcassar** [comment] 2020-10-07 10:13
Can we please have an update on this issue? 

I can confirm that @cmaycumber's solution works, but query parameters are an essential feature of web apps. We often don't have control over the code that is calling the uri and can't enforce the addition of a trailing slash.

In my case, I am unable to use [Utterances](https://utteranc.es/) until this issue is resolved since the token is appended to a callback uri that does not a '/'.

**Comment by KLaci** [comment] 2020-11-03 11:01
Any progress with this? It's not okay that I have to update all my links to the ridiculously looking `/page/?param=value` structure due to the breaking change in Amplify's redirect behavior. I seriously consider migrating to Netlify because of this issue.

**Comment by Lasim** [comment] 2020-12-31 22:18
Hi, can someone please provide an update for this issue?
I'm using VueJS with nasty workaround for URL parameter.

**Comment by santinogue** [comment] 2021-02-19 18:31
Any updates? It is a very necessary feature.

**Comment by jimmyn** [comment] 2021-03-02 10:01
I'm also struggling with this. We have moved our website to a new domain and we need to redirect all requests including query params. This is a critical issue for us. Is there any workaround right now?

**Comment by Calandri** [comment] 2021-03-15 14:38
Any update?!?!

**Comment by Calandri** [comment] 2021-03-24 19:57
Hello, WE NEED THIS feature? Look like AWS is not interest in keepe paying costumer. And AWS it's not free. Please. FIX this BUG

**Comment by iceye** [comment] 2021-03-30 21:41
+1, same issue, after hours of tests it's impossible to migrate existing routes to amplify. This missing feature it's more than blocking

**Comment by Coelmount** [comment] 2021-04-27 09:20
same issue here

I confirm however that https://myapp.amplifyapp.com/sso/?param1=value1&param2=value2&.... has the desired effect however, this additional / before the ? is not viable.

Can this be fixed please?

**Comment by caycecollins** [comment] 2021-06-09 19:17
> same issue here
> 
> I confirm however that https://myapp.amplifyapp.com/sso/?param1=value1&param2=value2&.... has the desired effect however, this additional / before the ? is not viable.
> 
> Can this be fixed please?

I agree. if we construct the links ourselves and send it to somebody, then manually adding the slash would be a fine solution.

However, if a user is at `/shop?brand=SomeBrand` and wants to bookmark the page, they will get sent back to `/shop/` when using the bookmark later.

**Comment by dparrelli** [comment] 2021-07-08 08:07
For those who are using the trailing slash hack to resolve this issue, how are you preventing the trailing slash from being automatically removed when the URL loads?

eg. When I refresh a page with a URL that has a query string, this is what happens to the URL:
https://myapp.com/section/?id=1   -->   https://myapp.com/section?id=1   -->   https://myapp.com/section

**Comment by leofrozenyogurt** [comment] 2021-08-18 20:35
> For those who are using the trailing slash hack to resolve this issue, how are you preventing the trailing slash from being automatically removed when the URL loads?
> 
> eg. When I refresh a page with a URL that has a query string, this is what happens to the URL:
> https://myapp.com/section/?id=1 --> https://myapp.com/section?id=1 --> https://myapp.com/section

this is still an ongoing issue; so the workaround hack isnt great for now

**Comment by pankajsoni19** [comment] 2021-08-20 05:13
Is there any ETA on resolving this? Most of our sites are on Amplify. For this particular issue we would have to migrate couple of our sites to firebase hosting.

**Comment by Calandri** [comment] 2021-08-20 06:13
We are going to migrate 4 sites next week for this issue, it's 10 months
that we are asking to solve this issue

Il giorno ven 20 ago 2021 alle ore 07:13 Pankaj Soni <
***@***.***> ha scritto:

**Comment by Lasim** [comment] 2021-08-20 18:34
Any updates?

**Comment by borisilic** [comment] 2021-08-21 01:08
Anyone have a good resource for removing Amplify hosting but keeping the rest of the infrastructure? The workaround doesn't work amazingly well with Angular.

**Comment by pankajsoni19** [comment] 2021-08-21 06:09
I confirm things work well with firebase hosting. The deployment/migration is a breeze too, without much downtime.

**Comment by Calandri** [comment] 2021-08-21 09:36
Great I will do that soon

Il Sab 21 Ago 2021, 08:09 Pankaj Soni ***@***.***> ha scritto:

**Comment by l-hendriks** [comment] 2021-09-22 11:31
How can this still not work? We don't have a single page app so the redirect rule fix doesn't apply. UTM tracking is impossible now on any amplify app ever, we can't ask of people to always include a trailing slash (which is a bad workaround because refreshing removes the querystring again anyway). It's issue number 97, so it's basically been reported since day 1?!

We are fixing this by deploying after the test stage to our own S3 bucket and ignoring the CD deploy and verify steps. But to break out of Amplify's features just to make a trivial web feature work baffles me

**Comment by l-hendriks** [comment] 2021-09-22 14:27
The issue has several components:

- When S3 static web hosting encounters an url without trailing slash, it tries "x.html". If that can't be found, it will do a 301/2 redirect to "x/" and then tests "x/index.html", which works with static websites like Gatsby. S3 removes the query string and there is no way around it
- Gatsby by default (or actually reach router) wants to remove trailing slashes

I fixed this by doing the following things:

**For Gatsby**
Install gatsby plugin to force trailing slashes (https://www.gatsbyjs.com/plugins/gatsby-plugin-force-trailing-slashes/) -- this is only specific to gatsby

**To fix the S3 redirect**
You can only fix this by routing to a trailing slash before going to S3, so this has to be done in cloudfront with a lambda@edge function, like this one: https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/issues/1

However, you can't change the cloudfront settings of an amplify deploy, so I added this in the test phase of the amplify.yml deploy script:

```
test:
  phases:
    test:
      commands:
        # Do test things

        # This would be better in postTest, but that runs even when test fails
        - echo "Deploying site to S3"
        # You could here add a thing to exit when not main branch for example
        - aws s3 sync public s3://CUSTOM_S3_BUCKET
        - aws cloudfront create-invalidation --distribution-id YOUR_ID --paths '/*'
        - rm -rf public/*
        - touch public/hoi # necessary for successful pipeline
```

This deploys your public folder (or change into dist) into your own bucket that you can configure using cloudfront to use the lambda@edge. It then removes the public folder and deploys nothing in the amplify bucket. So you basically use everything from amplify, but circumvent the actual deploy.

I can confirm this 100% works for `/x?a=b` and `/x/?a=b` and the querystring also stays when redirecting etc :)

however, it still is quite annoying we need this quite elaborate workaround to get something simple as querystrings working, but I do understand why this is such a long standing issue for the Amplify team: it's actually a limitation of S3.

However, a possible permanent fix would be to allow origin requests in the amplify cloudfront distributions from the amplify settings page.

**Comment by jonathanbravecredit** [comment] 2021-11-20 06:00
@watilde your solution worked perfectly. I had to re-order my rules slightly in a different order of preference but after that, it worked perfectly.

**Comment by tmosmant** [comment] 2022-02-27 16:14
Hello, this is still needed and unfortunately the workarounds are still workarounds...

**Comment by Calandri** [comment] 2022-02-27 16:23
AGree! FIXXXXXXX

**Comment by Calandri** [comment] 2022-02-27 16:23
AGREE

Il giorno dom 27 feb 2022 alle ore 17:14 Thomas Mosmant <
***@***.***> ha scritto:

**Comment by parikls** [comment] 2022-05-04 17:23
Any updates regarding this? It **should not** work like this

**Comment by l-hendriks** [comment] 2022-05-04 17:39
No it still works like that afaik, we're currently moving away from amplify ci/cd completely to github actions so we have more control. The "solution" I posted earlier is still how we handle things which is running stable for months now, but it's kind of a non-solution.

**Comment by swaminator** [comment] 2022-05-04 21:54
@parikls @l-hendriks we just launched support for this: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#query-strings-and-path-parameters

**Comment by apal21** [comment] 2022-05-10 07:21
@swaminator Thanks for the update.

This is working properly if I define the redirects manually like this:
```
/foo?bar=<value> => /foo/?bar=<value>
```

But it is not working for dynamic URLs using `*`. Sometimes it is throwing `502`.
Any idea on how to implement this?

**Comment by Narrator** [comment] 2022-05-16 21:17
@apal21 Could you please share the exact redirect rule that you're using and elaborate on your intended behavior? Thank you!

**Comment by eliottparis** [comment] 2022-05-17 16:20
@swaminator Thanks for the update, but I think we are still facing the same problem here, query parameters are not passed to the rewritten URL.

Our redirection rule:

```json
{
   "source": "https://foo.com",
   "target": "https://www.foo.com",
   "status": "301",
   "condition": null
}
```

```console
$ curl -v -L https://foo.com/player.html?uid=3000
> GET /player.html?uid=3000 HTTP/2
> Host: foo.com
> 
< HTTP/2 301 
< content-length: 0
< location: https://www.foo.com/player.html
< server: CloudFront

> GET /player.html HTTP/2
> Host: www.foo.com
```

From the [documentation](https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#query-parameters):

> Query parameters
You can use query parameters for more control over your URL matches. Amplify forwards all query parameters to the destination path for 301 and 302 redirects, with the following exceptions:
> - If the original address includes a query string set to a specific value, Amplify doesn’t forward query parameters. In this case, the redirect only applies to requests to the destination URL with the specified query value.
> - If the destination address for the matching rule has query parameters, query parameters aren’t forwarded. For example, if the destination address for the redirect is [https://example-target.com?q=someParam](https://example-target.com/?q=someParam), query parameters aren’t passed through.

I don’t think we are in the exceptions mentioned above, or do we?

**Comment by apal21** [comment] 2022-05-18 10:09
@Narrator 
We have some redirect URLs for OAuth like this:
```
/salesforce/auth/callback?code=<code> => /salesforce/auth/callback/?code=<code>
/google/auth/callback/?code=<code> => /google/auth/callback/?code=<code>
```

But I have to put all the rules manually. In some cases, there are multiple query params (`?code=<code>&state=<state>`).
I thought since this is a pattern, is there a way to have a single rule I can write for this? That way I have to maintain a single redirect only.

Thanks.

**Comment by Jun711** [comment] 2022-06-07 20:54
@Narrator 
It doesn't seem to support SPA redirection with query string params
I created a thread here but I haven't got any reply https://github.com/aws-amplify/amplify-hosting/issues/2781

For example
https://our-website.com/application/path1?param1=XXX&param2=YYY

application is an SPA
path1 is a a path managed by the SPA

I tried with 301 redirect but it didn't work.
It worked with rewrite but it would drop the query params

**Comment by sadjow** [comment] 2022-06-29 16:19
Some more details for SSG(Static Site Generator) websites:

In a Static Site Generator, when we deploy generated HTML to Amplify. It removes the query params in any case when the page points to an index.html file when inside subfolders. 

On the index.html in the root domain, it works really fine. So, `www.example.com?utm_source=foo` redirects well to `www.example.com/?utm_source=foo` without any problems.

**But the issue is when it is in a sub path/folder:**

When we have a file like this: `contact/index.html` when the browser access `www.example.com/contact?utm_source=foo` it removes the queries parameters and always redirects to `www.example.com/contact/` when if we do not have any rewrite rule with the query strings.

An example with Nuxt.js' default behavior: for a `pages/contact.vue` page component. It generates the HTML file in a subPath like this `/contact/index.html`. And Amplify automatically points paths on `www.example.com/contact` to it. Amplify appends the trailing slash `/` in this case. An alternative solution is to change the default behavior of Nuxt and set the generator's `[subFolders](https://nuxtjs.org/docs/directory-structure/dist/#the-subfolders-property)` option to `false`. This will make Nuxt's generator to generate a contact.html file instead instead of contact/index.html. So, Amplify will not redirect from `www.example.com/contact?utm_source=foo` to `www.example.com/contact/` and it will jeep the browser at `www.example.com/contact?utm_source=foo`. This is an alternative solution/ workaround. 

I believe there is a bug in the code path where Amplify needs to append the trailing slash `/` and removes the original query parameters.

**Comment by IkKan** [comment] 2022-07-23 12:26
Almost 3 years later and there's no fix yet... 😞

**Comment by l-hendriks** [comment] 2022-07-24 08:28
yeah it could be fixed easily if there just was an option to deploy it on your own S3 bucket instead of Amplify's. You can then add your own cloudfront distribution and have full control of what you need

**Comment by iyunusov** [comment] 2022-08-18 18:44
This is some sorta bull-shit, how could query params bother your setup at first place team amplify? Resolution must be initiated before a workaround.

**Comment by DevPowers** [comment] 2022-09-06 00:16
This is happening to me as well, I spent a whole day debugging to figure out the cause and find myself here. Sad to see the issue isn't closed yet after 3+ years

**Comment by DevPowers** [comment] 2022-09-06 02:15
Also I haven't seen it mentioned anywhere but if you just use a url with 'www', the query params are preserved. 

So trying to navigate to 'example.com/path?query=query1' --results in-->  'example.com/path' 

But if you just throw in the 'www' (essentially avoiding the redirect in the first place). Such as:
-  navigating to 'www.example.com/path?query=query1' --succesfully results in-->  'www.example.com/path?query=query1'

Not a fix at all or even a work around. Just a tip to try and avoid the redirect in the first place.

**Comment by simoneagostinelli** [comment] 2022-09-07 18:59
@DevPowers you saved my night!

**Comment by dev-sym** [comment] 2023-05-25 01:03
Any hope for this issue to be fixed?

**Comment by sadjow** [comment] 2023-05-25 01:18
Believe it or not, the following works:

In the AWS Amplify rewrites section:

- Source address: `</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json|webp)$)([^.]+$)/>`
- Target address: `/`
- Type: `200 (Rewrite)`

**Comment by dev-sym** [comment] 2023-05-25 01:30
Unfortunately, this doesn't work for me, I am redirecting www to non-www while trying to keep the query string.

**Comment by ChoiYongWon** [comment] 2023-06-05 08:14
this solution works for me
the whole rewrite and redirection configuration as below

```text
[
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "404-200",
        "condition": null
    },
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]
```

**Comment by smada2108-happly** [comment] 2023-06-22 03:51
> this solution works for me the whole rewrite and redirection configuration as below
> 
> ```
> [
>     {
>         "source": "/<*>",
>         "target": "/index.html",
>         "status": "404-200",
>         "condition": null
>     },
>     {
>         "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
>         "target": "/index.html",
>         "status": "200",
>         "condition": null
>     }
> ]
> ```

This is so close to working for me but I lose my custom font when I have this rule :(

**Comment by seanaye** [comment] 2023-08-29 15:40
@ChoiYongWon Where does that JSON go? I cant find any docs on specifying the redirect rules outside of the amplify console web UI. I would prefer to specify this in code rather than the horrible AWS UI

**Comment by trandaison** [comment] 2024-01-10 08:13
It's 2024 and the issue is still there...

**Comment by swaminator** [comment] 2024-01-23 00:28
@trandaison could you explain what you mean by the trailing slash not working?

**Comment by trandaison** [comment] 2024-01-26 08:39
@swaminator Sorry for the confusion.
In my case, the root cause was the cloudfront was not forwarding the query string to the amplify. So adding the traling slash was not working. The problem was not on the amplify itself.

**Comment by mauerbac** [comment] 2024-02-20 16:09
Hello everyone -- this issue has been resolved! Now redirects will preserve the query parameter passed to it. Please let me know if you see the correct behavior. @trandaison @dev-sym @iyunusov 

<img width="510" alt="Screenshot 2024-02-20 at 11 02 48 AM" src="https://github.com/aws-amplify/amplify-hosting/assets/1507886/b83d4131-9df6-44b7-9ba3-35363269a0f2">

**Closed by mauerbac** 2024-02-20 16:09 UTC
Labels: feature-request, redirects

**Comment by sadjow** [comment] 2024-02-20 16:21
@mauerbac, is it required to declare all the query parameters to it to keep the query parameters in the URL? For example, UTM parameters:

/some-page?utm_content=foo&utm_medium=bar

/some-page/?utm_content=foo&utm_medium=bar

Should we declare variables in all redirects to preserve them, or is this fix still pending deployment?
