### ISSUE TITLE
Amplify Preview Status not reflecting correctly in GITHUB pull Request

### ISSUE THREAD

**Issue by Chashall316** [aws-amplify/amplify-hosting#1458] opened 2021-01-14 18:19 UTC
**Describe the bug**
GITHUB Pull request will sometimes sit in QUEUE status even if the Amplify Preview status is completed preventing us from completing the pull request

**To Reproduce**
1.  Initiate a pull request with a Preview check requirement

**Expected behavior**
Once Preview check completes successfully in amplify, it should reference complete in GITHUB to allow the pull request to complete

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by michaelbrewer** [comment] 2021-01-14 18:28
Amplify ID: d1ytom7j4ziit6

GitHub reflects that the build is queued:
<img width="917" alt="Screen Shot 2021-01-14 at 10 17 43 AM" src="https://user-images.githubusercontent.com/5442469/104632664-e8531c80-5652-11eb-8e60-aad0335f2e66.png">

But on Amplify it is shown as complete
<img width="1082" alt="Screen Shot 2021-01-14 at 10 22 29 AM" src="https://user-images.githubusercontent.com/5442469/104632654-e6895900-5652-11eb-9049-5d9c3cee278c.png">

**Comment by hsspain** [comment] 2021-01-19 17:14
@Chashall316 @michaelbrewer We are looking at this as a priority and will update you when we have a resolution.

**Comment by noahgorstein** [comment] 2021-05-13 18:10
I am seeing this same behavior if a commit is pushed to the repository, triggering another build while the last build hasn't finished yet. The check never finishes despite the build actually completing in amplify.

**Comment by nlaffey-icario** [comment] 2021-06-02 18:20
I'm also experiencing the same behavior that @noahgorstein is describing.

**Comment by michaelbrewer** [comment] 2021-06-02 18:26
@hsspain  any progress on this? This effects how we do continuous integration

**Comment by Mhm0ud** [comment] 2021-08-10 08:02
I'm also experiencing the same behavior that @noahgorstein is describing.

**Comment by noahgorstein** [comment] 2021-08-10 13:08
@hsspain any update on this issue?

**Comment by grimsa** [comment] 2021-09-28 19:51
We encountered this issue today too.

Looking at the comments, it seems there may be a pattern of multiple people being active on this issue on the same date (possibly due to encountering the same issue):
- 2 people comment on Jun 2
- 2 people comment on Aug 10
- 2 people comment today

**Comment by noahgorstein** [comment] 2021-09-28 20:03
I don't think there's a pattern. I can reproduce this issue at anytime, any day. I'm not super familiar with how to get the Amplify team's attention on this. Does anyone know who we can tag on this issue?

As simple as this preview status issue is, it really holds up my team's PR review process. I've had to educate my team members to push a "dummy" commit to get the status to refresh even though the preview is built successfully. It would be great not to have to rely on this workaround. Any help is much appreciated!

**Comment by LucasLemanowicz** [comment] 2022-01-05 22:43
I've also been encountering this issue fairly consistently for the past couple of months as well (most recently yesterday). Agree with @noahgorstein that this can lead to slower review processes, and failing builds accidentally getting merged in.

**Comment by andrew0x1A4** [comment] 2022-02-04 05:06
I have also just experienced this.  Not only did the preview build complete successfully and not have the success reflected in GitHub properly. 

Additionally, but probably worthy of a separate issue, the Amplify Builds are taking forever! From 10 to nearly 20 minutes for a very small, frontend only, Next.js project. Locally this is less than a second build. The Preview Builds feel like they take the longest though I can't seem to see a history of the PR builds. The last one was about 18 minutes though, and never updated GitHub with success.

**Comment by DanielJSottile** [comment] 2022-04-12 19:16
For my team, this is still an issue.  The checks are not consistent either, as some will pass/fail, while others will stall indefinitely. Build/deployment succeeds but we can't use the check right now to verify PR's

**Comment by victorccccc** [comment] 2022-04-24 21:47
Sorry for the inconvenience , we've fixed this issue. Feel free to reopen if issue persists

**Closed by victorccccc** 2022-04-24 21:47 UTC
Labels: bug
