### ISSUE TITLE
Unable to delete application or environment

### ISSUE THREAD

**Issue by ehouse** [aws-amplify/amplify-hosting#2548] opened 2022-01-28 05:52 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2eluhxt9l163y

### Region

us-east-1

### Amplify Console feature

Backend builds, Build settings

### Describe the bug

I'm unable to delete my application from the console. When I do my console log is filled with JS exceptions and the site appears to be in an unhealthy state. It appears that I have an environment in my application with partial data. I'm unable to delete it from my console as well. 

I've tried to sync up my cli environment but that also appears to not want to delete/modify the ghost environment. 

```
POST https://amplifybackend.us-east-1.amazonaws.com/backend/d2eluhxt9l163y/remove

Error occured during Create backend using processor: ResourceNotFoundException: ResourceNotFoundException - An error occurred while processing your request: S3 bucket amplify-coven-devel-130850-deployment or object #current-cloud-backend.zip was not found.

Uncaught (in promise) ValidationError: Stack [amplify-coven-devel-130850] does not exist
```

![Capture](https://user-images.githubusercontent.com/1088895/151494517-8f89135d-ec73-4e28-8a31-8db56dca87b8.PNG)

![Capture](https://user-images.githubusercontent.com/1088895/151495194-f849bb4a-ad37-46b9-898d-2cd685b9bf42.PNG)

### Expected behavior

I expect that the delete application button works. I expect that the environment delete button works. 

### Reproduction steps

1. Click delete on the App

### Build Settings

```yaml
n/a
```

**Comment by hloriana** [comment] 2022-01-28 18:21
Hi @ehouse 👋🏽 thank you for providing reproduction steps. Can you try deleting the backends with this AWS CLI command: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

**Comment by ehouse** [comment] 2022-01-28 18:46
That worked! Thank you for the quick turnout on a resolution.

**Comment by akash87** [comment] 2022-02-17 13:25
Thank you this worked! There was an error when calling the DeleteBackendEnvironment operation: The security token included in the request is invalid. but it was resolved with passing --profile <aws_profile> parameter.

**Comment by dpalme3160** [comment] 2022-06-03 03:07
> Hi @ehouse 👋🏽 thank you for providing reproduction steps. Can you try deleting the backends with this AWS CLI command: `aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>`

delete-backend-environment command does not exist in cli

**Comment by akash87** [comment] 2022-06-03 04:56
@dpalme3160  - https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html

**Comment by dpalme3160** [comment] 2022-06-03 05:27
⚠️ The Amplify CLI can NOT find command:  delete-backend-environment
Plugin scan failed.
Error: EACCES: permission denied, open '/Users/douglaspalme/.amplify/plugins.json'
    at Object.openSync (fs.js:497:3)
    at Object.openSync (pkg/prelude/bootstrap.js:739:32)
    at Object.writeFileSync (fs.js:1528:35)
    at Function.writeJson (/snapshot/repo/build/node_modules/amplify-cli-core/lib/jsonUtilities.js:75:8)
    at writePluginsJsonFile (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/plugin-helpers/access-plugins-file.js:37:38)
    at scanPluginPlatform (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/plugin-helpers/scan-plugin-platform.js:72:52)
    at async scan (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/plugin-manager.js:137:24)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:125:30) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/douglaspalme/.amplify/plugins.json'
}
🛑 Plugin scan failed.
Error: Plugin scan failed.
    at scan (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/plugin-manager.js:143:15)
    at async Object.run (/snapshot/repo/build/node_modules/@aws-amplify/cli-internal/lib/index.js:125:30)
douglaspalme@MacbookPro20220324 iOS Getting Started %

**Comment by dpalme3160** [comment] 2022-06-03 05:28
douglaspalme@MacbookPro20220324 iOS Getting Started % sudo amplify delete-backend-environment
Password:
⚠️ The Amplify CLI can NOT find command:  delete-backend-environment

amplify <command> <subcommand>

  init                         Initializes a new project, sets up deployment resources in the cloud, and makes your project ready for Amplify.                              
  configure                    Configures the attributes of your project for amplify-cli, such as switching front-end framework and adding/removing cloud-provider plugins. 
  push                         Provisions cloud resources with the latest local developments.                                                                               
  pull                         Fetch upstream backend environment definition changes from the cloud and updates the local environment to match that definition.             
  publish                      Executes amplify push, and then builds and publishes client-side application for hosting.                                                    
  serve                        Executes amplify push, and then executes the project's start command to test run the client-side application locally.                        
  status [<category> ...]      Shows the state of local resources not yet pushed to the cloud (Create/Update/Delete).                                                       
  status -v [<category> ...]   Shows the detailed verbose diff between local and deployed resources, including cloudformation-diff                                          
  delete                       Deletes all of the resources tied to the project from the cloud.                                                                             
  <category> add               Adds a resource for an Amplify category in your local backend                                                                                
  <category> update            Update resource for an Amplify category in your local backend.                                                                               
  <category> push              Provisions all cloud resources in a category with the latest local developments.                                                             
  <category> remove            Removes a resource for an Amplify category in your local backend.                                                                            
  <category>                   Displays subcommands of the specified Amplify category.                                                                                      
  mock                         Run mock server for testing categories locally.                                                                                              
  codegen                      Generates GraphQL statements(queries, mutations and eventHandlers) and type annotations.                                                     
  env                          Displays and manages environment related information for your Amplify project.                                                               
  console                      Opens the web console for the selected cloud resource.                                                                                       
  logout                       If using temporary cloud provider credentials, this logs out of the account.                                                                 
  upgrade                      Download and install the latest version of the Amplify CLI                                                                                   
  uninstall                    Remove all global Amplify configuration files and uninstall the Amplify CLI. This will not delete any Amplify projects.                      

where <category> is one of: notifications, api, auth, custom, storage, analytics, function, geo, hosting, interactions, predictions, xr

**Comment by UltraEricB** [comment] 2022-06-03 19:07
Thank you! Solved my problem...

aws amplify delete-backend-environment --app-id <YOUR_APP_ID> --environment-name <THE_BACKEND_ENVIRONMENT_NAME>

**Comment by johnpc** [comment] 2022-09-27 01:02
When deleting via Amplify console, the error reported

```
ResourceNotFoundException - An error occurred while processing your request: S3 bucket amplify-coven-devel-130850-deployment or object #current-cloud-backend.zip was not found.
```

has been fixed. you should be able to re-try deleting your app from Amplify console.

**Comment by Jay2113** [comment] 2024-02-21 21:30
Closing since the issue has been fixed.

**Closed by Jay2113** 2024-02-21 21:30 UTC
Labels: bug, console
